Generalization: Support understands protocol
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/eachSection b/bin/eachSection
--- a/bin/eachSection
+++ b/bin/eachSection
@@ -39,12 +39,46 @@ separatorPattern='^-\{2,3\}$'
 isSeparatorBelow=
 typeset -a suppressedMatchedArg=(--suppress-matched)
 typeset -a args=()
+typeset -a understandsArgs=()
+option() { :; }
+parameter() { :; }
+parameterToSep() { :; }
+argCount() { :; }
+endOfOptionsAndParameters() { :; }
+noUnderstand() { :; }
+delegateUnderstand() { :; }
+typeset -A understandsSubtopics=()
+isUnderstandSubtopic() {
+    [ $# -gt 0 -a ${#understandsSubtopics[@]} -gt 0 ] || return 0
+    local subtopic; for subtopic
+    do
+	[ "${understandsSubtopics["$subtopic"]}" ] && return 0
+    done
+    return 1
+}
 while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--understand-for)
+			understandsArgs+=("$1" "${2?}"); shift; understandsSubtopics["$1"]=t; shift;;
+	--understands)	shift
+			option() { isUnderstandSubtopic "$@" || exit 1; printf 1; exit 0; }
+			parameter() { isUnderstandSubtopic "$@" || exit 1; printf 2; exit 0; }
+			parameterToSep() { argCount "$@"; }
+			argCount() { local argCount="${1:?}"; shift; isUnderstandSubtopic "$@" || exit 1; printf $argCount; exit 0; }
+			endOfOptionsAndParameters() { exit 99; }
+			noUnderstand() { exit 1; }
+			delegateUnderstand() { eachSplit --splitter csplit \; "${understandsArgs[@]}" --understands "$@"; exit $?; }
+
+			# As a wrapper, if the wrappee understands the argument, accept that. For
+			# anything of our customizations, we need to say whether we understand it. (But
+			# we may delegate to the wrappee with renamed arguments.)
+			eachSplit --splitter csplit \; "${understandsArgs[@]}" --understands "$@" && exit 0
+			;;
+
 	--section-separator|-S)
-			shift; separatorPattern="${1:?}"; shift;;
+			shift; separatorPattern="${1:?}"; shift; parameter split;;
 	--section-info-include-separator)
 			shift
 			case "${1:?}" in
@@ -58,15 +92,16 @@ do
 			esac; shift
 			suppressedMatchedArg=()
 			args+=(--piece-modifier-exec sed -i "/${separatorPattern//\//\\/}/d" -- "${EACHSPLIT_MODIFIER_MARKER:-{\}}" "${EACHSPLIT_MODIFIER_END:-;}")
+			parameter split
 			;;
-	--section-*)	args+=("${1/#--section-/--piece-}"); shift;;
+	--section-*)	renamedArg="${1/#--section-/--piece-}"; shift; args+=("$renamedArg"); delegateUnderstand "$renamedArg" "$@";;
 
 	# Note: In order to parse -- properly, the --section-*-exec parameters would
 	# have to be fully parsed, too, because they can contain --. We go the lazy
 	# route and just assume that anything after -- doesn't start with --section-*.
 	#--)		args+=("$1"); shift; break;;
 
-	*)		args+=("$1"); shift;;
+	*)		args+=("$1"); shift; delegateUnderstand "$@";;	# This asks the wrappee again, but this time actually fails and exits.
     esac
 done
 
