each{Arg,Dir,File,Split}: FIX: Need to define and execute reportProgress() inside the runWith script
Progress reporting needs to be done during the execution, not simply during the creation of the commands to be executed - that's too early.
Unfortunately, that means that most of the progress setup needs to be duplicated. Maintain the reportProgress() function to also have the broken pipe handling.

diff --git a/bin/eachArg b/bin/eachArg
--- a/bin/eachArg
+++ b/bin/eachArg
@@ -142,15 +142,7 @@ if [ $# -eq 0 ]; then
 fi
 
 if [ "$hasProgressNotification" ] && [ -n "$progressSink" ]; then
-    exec 4> >(progressNotification --to "$progressSink" ${EACHARG_ARG_WHAT:+--prepend-count "$EACHARG_ARG_WHAT"} --count-to $# 2>/dev/null)
-
-    reportProgress()
-    {
-	trap 'reportProgress() { :; }; trap PIPE' PIPE
-	printf '%s\n' "$*" >&4 2>/dev/null  # Silence "printf: write error: Broken pipe"
-    }
-else
-    reportProgress() { :; }
+    typeset -a progressNotificationCommand=(progressNotification --to "$progressSink" ${EACHARG_ARG_WHAT:+--prepend-count "$EACHARG_ARG_WHAT"} --count-to $#)
 fi
 
 setStatus()
@@ -163,30 +155,47 @@ isHeader=
 case "$with" in
     runWith*)
 	[ ${#runWithPromptArgs[@]} -eq 0 ] && runWithPromptArgs=(--worst-status)
-	for arg
-	do
-	    if [ ! "$isFirst" ] && [ -n "$betweenCommand" ]; then
-		if [ "${betweenCommand:$((${#betweenCommand} - 1))}" = ';' ]; then
-		    printf '%s ' "$betweenCommand"  # Prepend the BETWEEN-COMMAND to the next ARGUMENT's execution (so there's no separate prompt) if it ends with a semicolon. Its exit status is then ignored.
-		else
-		    printf '%s\n' "$betweenCommand" # Use a separate prompt (and with it consider its exit status).
+	{
+	    printf ' exec 4> >('
+	    printf '%q ' "${progressNotificationCommand[@]}"
+	    printf '2>/dev/null); reportProgress() { trap "reportProgress() { :; }; trap PIPE" PIPE; printf %%s\\\\n "$*" >&4 2>/dev/null; }\n'
+
+	    for arg
+	    do
+		if [ ! "$isFirst" ] && [ -n "$betweenCommand" ]; then
+		    if [ "${betweenCommand:$((${#betweenCommand} - 1))}" = ';' ]; then
+			printf '%s ' "$betweenCommand"  # Prepend the BETWEEN-COMMAND to the next ARGUMENT's execution (so there's no separate prompt) if it ends with a semicolon. Its exit status is then ignored.
+		    else
+			printf '%s\n' "$betweenCommand" # Use a separate prompt (and with it consider its exit status).
+		    fi
 		fi
-	    fi
 
-	    printf -v quotedArg '%q' "$arg"
-	    interpolatedCommands="${commands//"$argMarker"/$quotedArg}"
-	    typeset -a a=("$quotedArg")
-	    [ "$interpolatedCommands" = "$commands" ] || a=()
+		printf -v quotedArg '%q' "$arg"
+		interpolatedCommands="${commands//"$argMarker"/$quotedArg}"
+		typeset -a a=("$quotedArg")
+		[ "$interpolatedCommands" = "$commands" ] || a=()
 
-	    reportProgress "$arg"
-	    printf '%s ' "$interpolatedCommands" "${a[@]}"
-	    printf '\n'
-	    isFirst=
-	done | ${with:?} "${runWithPromptArgs[@]}"
+		printf ' reportProgress %q || :\n' "$arg"
+		printf '%s ' "$interpolatedCommands" "${a[@]}"
+		printf '\n'
+		isFirst=
+	    done
+	} | ${with:?} "${runWithPromptArgs[@]}"
 	;;
     header)
 	isHeader=t;&
     '')
+	if [ "$hasProgressNotification" ] && [ -n "$progressSink" ]; then
+	    exec 4> >("${progressNotificationCommand[@]}" 2>/dev/null)
+	    reportProgress()
+	    {
+		trap 'reportProgress() { :; }; trap PIPE' PIPE
+		printf '%s\n' "$*" >&4 2>/dev/null  # Silence "printf: write error: Broken pipe"
+	    }
+	else
+	    reportProgress() { :; }
+	fi
+
 	status=0
 	for arg
 	do
diff --git a/bin/eachDir b/bin/eachDir
--- a/bin/eachDir
+++ b/bin/eachDir
@@ -216,15 +216,7 @@ fi
 
 if [ "$hasProgressNotification" ] && [ -n "$progressSink" ]; then
     typeset progressCountToArgs=(--count-to $#); [ "$isFixedNumberOfDirs" ] || progressCountToArgs=()
-    exec 4> >(progressNotification --to "$progressSink" ${EACHDIR_DIR_WHAT:+--prepend-count "$EACHDIR_DIR_WHAT"} "${progressCountToArgs[@]}" 2>/dev/null)
-
-    reportProgress()
-    {
-	trap 'reportProgress() { :; }; trap PIPE' PIPE
-	printf '%s\n' "$*" >&4 2>/dev/null  # Silence "printf: write error: Broken pipe"
-    }
-else
-    reportProgress() { :; }
+    typeset -a progressNotificationCommand=(progressNotification --to "$progressSink" ${EACHDIR_DIR_WHAT:+--prepend-count "$EACHDIR_DIR_WHAT"} "${progressCountToArgs[@]}")
 fi
 
 setStatus()
@@ -237,38 +229,55 @@ isHeader=
 case "$with" in
     runWith*)
 	[ ${#runWithPromptArgs[@]} -eq 0 ] && runWithPromptArgs=(--worst-status)
-	eval '$dirSource "$@"' "${dirProcessor:+|}" "$dirProcessor" | while IFS=$'\n' read -r dirspec || [ -n "$dirspec" ]
-	do
-	    [ -d "$dirspec" ] || continue
+	{
+	    printf ' exec 4> >('
+	    printf '%q ' "${progressNotificationCommand[@]}"
+	    printf '2>/dev/null); reportProgress() { trap "reportProgress() { :; }; trap PIPE" PIPE; printf %%s\\\\n "$*" >&4 2>/dev/null; }\n'
 
-	    if [ ! "$isFirst" ] && [ -n "$betweenCommand" ]; then
-		if [ "${betweenCommand:$((${#betweenCommand} - 1))}" = ';' ]; then
-		    printf '%s ' "$betweenCommand"  # Prepend the BETWEEN-COMMAND to the next DIR's execution (so there's no separate prompt) if it ends with a semicolon. Its exit status is then ignored.
-		else
-		    printf '%s\n' "$betweenCommand" # Use a separate prompt (and with it consider its exit status).
+	    eval '$dirSource "$@"' "${dirProcessor:+|}" "$dirProcessor" | while IFS=$'\n' read -r dirspec || [ -n "$dirspec" ]
+	    do
+		[ -d "$dirspec" ] || continue
+
+		if [ ! "$isFirst" ] && [ -n "$betweenCommand" ]; then
+		    if [ "${betweenCommand:$((${#betweenCommand} - 1))}" = ';' ]; then
+			printf '%s ' "$betweenCommand"  # Prepend the BETWEEN-COMMAND to the next DIR's execution (so there's no separate prompt) if it ends with a semicolon. Its exit status is then ignored.
+		    else
+			printf '%s\n' "$betweenCommand" # Use a separate prompt (and with it consider its exit status).
+		    fi
 		fi
-	    fi
 
-	    printf -v quotedDirspec '%q' "$dirspec"
-	    if [ "$isLocalDir" ]; then
-		printf 'cd %q && ' "$dirspec"   # Previous COMMANDS may have changed the directory, so unconditionally do the chdir.
-		interpolatedCommands="${commands//"$dirMarker"/$quotedDirspec}"
-		f=()
-	    else
-		interpolatedCommands="${commands//"$dirMarker"/$quotedDirspec}"
-		typeset -a f=("$quotedDirspec")
-		[ "$interpolatedCommands" = "$commands" ] || f=()
-	    fi
+		printf -v quotedDirspec '%q' "$dirspec"
+		if [ "$isLocalDir" ]; then
+		    printf 'cd %q && ' "$dirspec"   # Previous COMMANDS may have changed the directory, so unconditionally do the chdir.
+		    interpolatedCommands="${commands//"$dirMarker"/$quotedDirspec}"
+		    f=()
+		else
+		    interpolatedCommands="${commands//"$dirMarker"/$quotedDirspec}"
+		    typeset -a f=("$quotedDirspec")
+		    [ "$interpolatedCommands" = "$commands" ] || f=()
+		fi
 
-	    reportProgress "$dirspec"
-	    printf '%s ' "$interpolatedCommands" "${f[@]}"
-	    printf '\n'
-	    isFirst=
-	done | ${with:?} "${runWithPromptArgs[@]}"
+		printf ' reportProgress %q || :\n' "$dirspec"
+		printf '%s ' "$interpolatedCommands" "${f[@]}"
+		printf '\n'
+		isFirst=
+	    done
+	} | ${with:?} "${runWithPromptArgs[@]}"
 	;;
     header)
 	isHeader=t;&
     '')
+	if [ "$hasProgressNotification" ] && [ -n "$progressSink" ]; then
+	    exec 4> >("${progressNotificationCommand[@]}" 2>/dev/null)
+	    reportProgress()
+	    {
+		trap 'reportProgress() { :; }; trap PIPE' PIPE
+		printf '%s\n' "$*" >&4 2>/dev/null  # Silence "printf: write error: Broken pipe"
+	    }
+	else
+	    reportProgress() { :; }
+	fi
+
 	status=0
 	exec 3<&0
 	: ${EACHDIR_HEADER_ID:="eachDir-$$-$RANDOM"}
diff --git a/bin/eachFile b/bin/eachFile
--- a/bin/eachFile
+++ b/bin/eachFile
@@ -219,16 +219,8 @@ if [ $# -eq 0 -a ${#findArgs[@]} -eq 0 ]; then
 fi
 
 if [ "$hasProgressNotification" ] && [ -n "$progressSink" ]; then
-    typeset progressCountToArgs=(--count-to $#); [ "$isFixedNumberOfFiles" ] || progressCountToArgs=()
-    exec 4> >(progressNotification --to "$progressSink" ${EACHFILE_FILE_WHAT:+--prepend-count "$EACHFILE_FILE_WHAT"} "${progressCountToArgs[@]}" 2>/dev/null)
-
-    reportProgress()
-    {
-	trap 'reportProgress() { :; }; trap PIPE' PIPE
-	printf '%s\n' "$*" >&4 2>/dev/null  # Silence "printf: write error: Broken pipe"
-    }
-else
-    reportProgress() { :; }
+    typeset -a progressCountToArgs=(--count-to $#); [ "$isFixedNumberOfFiles" ] || progressCountToArgs=()
+    typeset -a progressNotificationCommand=(progressNotification --to "$progressSink" ${EACHFILE_FILE_WHAT:+--prepend-count "$EACHFILE_FILE_WHAT"} "${progressCountToArgs[@]}")
 fi
 
 setStatus()
@@ -241,36 +233,53 @@ isHeader=
 case "$with" in
     runWith*)
 	[ ${#runWithPromptArgs[@]} -eq 0 ] && runWithPromptArgs=(--worst-status)
-	eval '$fileSource "$@"' "${fileProcessor:+|}" "$fileProcessor" | while IFS=$'\n' read -r filespec || [ -n "$filespec" ]
-	do
-	    if [ ! "$isFirst" ] && [ -n "$betweenCommand" ]; then
-		if [ "${betweenCommand:$((${#betweenCommand} - 1))}" = ';' ]; then
-		    printf '%s ' "$betweenCommand"  # Prepend the BETWEEN-COMMAND to the next FILE's execution (so there's no separate prompt) if it ends with a semicolon. Its exit status is then ignored.
-		else
-		    printf '%s\n' "$betweenCommand" # Use a separate prompt (and with it consider its exit status).
+	{
+	    printf ' exec 4> >('
+	    printf '%q ' "${progressNotificationCommand[@]}"
+	    printf '2>/dev/null); reportProgress() { trap "reportProgress() { :; }; trap PIPE" PIPE; printf %%s\\\\n "$*" >&4 2>/dev/null; }\n'
+
+	    eval '$fileSource "$@"' "${fileProcessor:+|}" "$fileProcessor" | while IFS=$'\n' read -r filespec || [ -n "$filespec" ]
+	    do
+		if [ ! "$isFirst" ] && [ -n "$betweenCommand" ]; then
+		    if [ "${betweenCommand:$((${#betweenCommand} - 1))}" = ';' ]; then
+			printf '%s ' "$betweenCommand"  # Prepend the BETWEEN-COMMAND to the next FILE's execution (so there's no separate prompt) if it ends with a semicolon. Its exit status is then ignored.
+		    else
+			printf '%s\n' "$betweenCommand" # Use a separate prompt (and with it consider its exit status).
+		    fi
 		fi
-	    fi
 
-	    if [ "$isLocalDir" ]; then
-		dirspec="$(dirname -- "$filespec")"
-		filespec="$(basename -- "$filespec")"
-		printf 'cd %q && ' "$dirspec"   # Previous COMMANDS may have changed the directory, so unconditionally do the chdir.
-	    fi
+		if [ "$isLocalDir" ]; then
+		    dirspec="$(dirname -- "$filespec")"
+		    filespec="$(basename -- "$filespec")"
+		    printf 'cd %q && ' "$dirspec"   # Previous COMMANDS may have changed the directory, so unconditionally do the chdir.
+		fi
 
-	    printf -v quotedFilespec '%q' "$filespec"
-	    interpolatedCommands="${commands//"$fileMarker"/$quotedFilespec}"
-	    typeset -a f=("$quotedFilespec")
-	    [ "$interpolatedCommands" = "$commands" ] || f=()
+		printf -v quotedFilespec '%q' "$filespec"
+		interpolatedCommands="${commands//"$fileMarker"/$quotedFilespec}"
+		typeset -a f=("$quotedFilespec")
+		[ "$interpolatedCommands" = "$commands" ] || f=()
 
-	    reportProgress "$filespec"
-	    printf '%s ' "$interpolatedCommands" "${f[@]}"
-	    printf '\n'
-	    isFirst=
-	done | ${with:?} "${runWithPromptArgs[@]}"
+		printf ' reportProgress %q || :\n' "$filespec"
+		printf '%s ' "$interpolatedCommands" "${f[@]}"
+		printf '\n'
+		isFirst=
+	    done
+	} | ${with:?} "${runWithPromptArgs[@]}"
 	;;
     header)
 	isHeader=t;&
     '')
+	if [ "$hasProgressNotification" ] && [ -n "$progressSink" ]; then
+	    exec 4> >("${progressNotificationCommand[@]}" 2>/dev/null)
+	    reportProgress()
+	    {
+		trap 'reportProgress() { :; }; trap PIPE' PIPE
+		printf '%s\n' "$*" >&4 2>/dev/null  # Silence "printf: write error: Broken pipe"
+	    }
+	else
+	    reportProgress() { :; }
+	fi
+
 	status=0
 	: ${EACHFILE_HEADER_ID:="eachFile-$$-$RANDOM"}
 	exec 3<&0
diff --git a/bin/eachSplit b/bin/eachSplit
--- a/bin/eachSplit
+++ b/bin/eachSplit
@@ -199,15 +199,7 @@ if [ ${#sectionFiles[@]} -eq 0 ]; then
 fi
 
 if [ "$hasProgressNotification" ] && [ -n "$progressSink" ]; then
-    exec 4> >(progressNotification --to "$progressSink" ${EACHARG_ARG_WHAT:+--prepend-count "$EACHARG_ARG_WHAT"} --count-to $# 2>/dev/null)
-
-    reportProgress()
-    {
-	trap 'reportProgress() { :; }; trap PIPE' PIPE
-	printf '%s\n' "$*" >&4 2>/dev/null  # Silence "printf: write error: Broken pipe"
-    }
-else
-    reportProgress() { :; }
+    typeset -a progressNotificationCommand=(progressNotification --to "$progressSink" ${EACHARG_ARG_WHAT:+--prepend-count "$EACHARG_ARG_WHAT"} --count-to $#)
 fi
 
 getSectionInfo()
@@ -229,22 +221,39 @@ isHeader=
 case "$with" in
     runWith*)
 	[ ${#runWithPromptArgs[@]} -eq 0 ] && runWithPromptArgs=(--worst-status)
-	for sectionFile in "${sectionFiles[@]}"
-	do
-	    printf -v quotedSectionFile '%q' "$sectionFile"
-	    interpolatedCommands="${commands//"$fileMarker"/$quotedSectionFile}"
-	    typeset -a f=("$quotedSectionFile")
-	    [ "$interpolatedCommands" = "$commands" ] || f=()
+	{
+	    printf ' exec 4> >('
+	    printf '%q ' "${progressNotificationCommand[@]}"
+	    printf '2>/dev/null); reportProgress() { trap "reportProgress() { :; }; trap PIPE" PIPE; printf %%s\\\\n "$*" >&4 2>/dev/null; }\n'
 
-	    reportProgress "$(getSectionInfo "$sectionFile")"
-	    printf '%s ' "$interpolatedCommands" "${f[@]}"
-	    printf '\n'
-	    isFirst=
-	done | ${with:?} "${runWithPromptArgs[@]}"
+	    for sectionFile in "${sectionFiles[@]}"
+	    do
+		printf -v quotedSectionFile '%q' "$sectionFile"
+		interpolatedCommands="${commands//"$fileMarker"/$quotedSectionFile}"
+		typeset -a f=("$quotedSectionFile")
+		[ "$interpolatedCommands" = "$commands" ] || f=()
+
+		printf ' reportProgress %q || :\n' "$(getSectionInfo "$sectionFile")"
+		printf '%s ' "$interpolatedCommands" "${f[@]}"
+		printf '\n'
+		isFirst=
+	    done
+	} | ${with:?} "${runWithPromptArgs[@]}"
 	;;
     header)
 	isHeader=t;&
     '')
+	if [ "$hasProgressNotification" ] && [ -n "$progressSink" ]; then
+	    exec 4> >("${progressNotificationCommand[@]}" 2>/dev/null)
+	    reportProgress()
+	    {
+		trap 'reportProgress() { :; }; trap PIPE' PIPE
+		printf '%s\n' "$*" >&4 2>/dev/null  # Silence "printf: write error: Broken pipe"
+	    }
+	else
+	    reportProgress() { :; }
+	fi
+
 	status=0
 	for sectionFile in "${sectionFiles[@]}"
 	do
