Revert "each{Dir,File}: ENH: Also accept -- before SIMPLECOMMAND"
Not a good idea, because in order to pass non-existing FILE(s) when -c|--command is used one now has to pass -- -- FILE [...], which is strange. And even that case isn't handled properly, because the addition of SIMPLECOMMAND doesn't check for an empty @cmd and mistakenly appends a quoted ''!
I'll handle this use case by allowing --exec instead.

This reverts commit 3b8f917cfa91179e165b26e4cc4585053dad863f.

diff --git a/bin/eachDir b/bin/eachDir
--- a/bin/eachDir
+++ b/bin/eachDir
@@ -12,9 +12,9 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s%s %s\n' "$(basename "$1")" '[-l|--local-dir]' "${hasProgressNotification:+ [--progress SINK]}" '[--with-[basename-]header [--separate-errors] [--color=(always|auto|never)|--no-color]|--with-prompt [--initial-status NUM] [--trailing-prompt|--no-trailing-prompt] [--no-output-no-prompt] [--no-output-no-error] [--emulate-prompt]] [--no-success-no-count|--no-count-on N] [--exit-on-success|--exit-on-failure|--exit-on NUM] [--worst-status] [--comment COMMENT] [--summarize-failed ERROR-TEXT [--summarize-failed-separator SEP]] [--between-command BETWEEN-COMMAND] [--usage-redirect COMMAND] -c|--command "COMMANDLINE" [...] | [--] SIMPLECOMMAND [...] [--] DIR [...] [-?|-h|--help]'
+    printf 'Usage: %q %s%s %s\n' "$(basename "$1")" '[-l|--local-dir]' "${hasProgressNotification:+ [--progress SINK]}" '[--with-[basename-]header [--separate-errors] [--color=(always|auto|never)|--no-color]|--with-prompt [--initial-status NUM] [--trailing-prompt|--no-trailing-prompt] [--no-output-no-prompt] [--no-output-no-error] [--emulate-prompt]] [--no-success-no-count|--no-count-on N] [--exit-on-success|--exit-on-failure|--exit-on NUM] [--worst-status] [--comment COMMENT] [--summarize-failed ERROR-TEXT [--summarize-failed-separator SEP]] [--between-command BETWEEN-COMMAND] [--usage-redirect COMMAND] -c|--command "COMMANDLINE" [...] | SIMPLECOMMAND [...] [--] DIR [...] [-?|-h|--help]'
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[...] -c|--command "COMMANDLINE" [...] | [--] SIMPLECOMMAND [...] -f|--find FIND-ARGS ...'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[...] -c|--command "COMMANDLINE" [...] | SIMPLECOMMAND [...] -f|--find FIND-ARGS ...'
 }
 printUsage()
 {
@@ -122,7 +122,6 @@ betweenCommand=
 usageRedirectCommand=
 runWithCommand=runWith
 typeset -a runWithPromptArgs=()
-hasSimpleCommand=
 while [ $# -ne 0 ]
 do
     case "$1" in
@@ -149,13 +148,9 @@ do
 			shift; betweenCommand="$1"; shift;;
 	--usage-redirect)
 			shift; usageRedirectCommand="$1"; shift;;
-	-|-[^-]*)	{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
-	*)		if [ "$1" = '--' ]; then
-			    shift
-			    [ "$hasSimpleCommand" ] && break    # This comes after SIMPLECOMMAND.
-			    hasSimpleCommand=t
-			fi
-			typeset -a dirspecs=()
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		typeset -a dirspecs=()
 			if ! containsGlob '@(--|--find|-f)' "$@"; then
 			    # Consume existing DIRs from behind.
 			    while [ $# -gt 0 ]
