ENH: Only print header if COMMAND has output; add --separate-errors to control stderr parsing

diff --git a/bin/eachDir b/bin/eachDir
--- a/bin/eachDir
+++ b/bin/eachDir
@@ -11,7 +11,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s%s %s\n' "$(basename "$1")" '[-l|--local-dir]' "${hasProgressNotification:+ [--progress SINK]}" '[--with-header|--with-prompt [--initial-status NUM] [--trailing-prompt|--no-trailing-prompt] [--no-output-no-prompt] [--no-output-no-error] [--emulate-prompt]] [--no-success-no-count|--no-count-on N] [--exit-on-success|--exit-on-failure|--exit-on NUM] [--worst-status] [--comment COMMENT] [--summarize-failed ERROR-TEXT [--summarize-failed-separator SEP]] [--between-command BETWEEN-COMMAND] [--usage-redirect COMMAND] -c|--command "COMMANDLINE" [...] | SIMPLECOMMAND [...] [--] DIR [...] [-?|-h|--help]'
+    printf 'Usage: %q %s%s %s\n' "$(basename "$1")" '[-l|--local-dir]' "${hasProgressNotification:+ [--progress SINK]}" '[--with-header [--separate-errors]|--with-prompt [--initial-status NUM] [--trailing-prompt|--no-trailing-prompt] [--no-output-no-prompt] [--no-output-no-error] [--emulate-prompt]] [--no-success-no-count|--no-count-on N] [--exit-on-success|--exit-on-failure|--exit-on NUM] [--worst-status] [--comment COMMENT] [--summarize-failed ERROR-TEXT [--summarize-failed-separator SEP]] [--between-command BETWEEN-COMMAND] [--usage-redirect COMMAND] -c|--command "COMMANDLINE" [...] | SIMPLECOMMAND [...] [--] DIR [...] [-?|-h|--help]'
     echo
     printf 'Usage: %q %s\n' "$(basename "$1")" '[...] -c|--command "COMMANDLINE" [...] | SIMPLECOMMAND [...] -f|--find FIND-ARGS ...'
 }
@@ -42,6 +42,12 @@ HELPDESCRIPTION
 	    progressNotification command.}
     --with-header   Print a header (containing the current DIR) before each
 		    execution.
+    --separate-errors	Do not combine command output and command errors into
+			one (paged) stream. Commands that just cause error
+			output won't have a header then. Error output will
+			remain on its separate file descriptor and will not be
+			paged. Useful if you want to suppress errors or handle
+			them separately.
     --with-prompt   Emulate a full prompt (as if invoking COMMAND) before each
 		    execution.
     --emulate-prompt	    Customizations of the prompt emulation around
@@ -114,6 +120,7 @@ makeAbsolute()
 }
 typeset -a findArgs=()
 with=
+errorRedir='2>&1'
 typeset -a commands=()
 betweenCommand=
 usageRedirectCommand=
@@ -128,6 +135,8 @@ do
 	--command|-c)	shift; commands+=(${commands:+;} "$1"); isNeedEval=t; shift;;
 	--progress)	shift; progressSink="$1"; shift;;
 	--with-header)	shift; with=header;;
+	--separate-errors)
+			shift; errorRedir='';;
 	--with-prompt)	shift; with=prompt; runWithCommand=runWithPrompt;;
 
 	--trailing-prompt|--no-trailing-prompt|--no-output-no-prompt|--no-output-no-error|--no-success-no-count|--exit-on-success|--exit-on-failure|--emulate-prompt|--worst-status)
@@ -252,6 +261,8 @@ case "$with" in
     *)
 	status=0
 	exec 3<&0
+	: ${EACHDIR_HEADER_ID:="eachDir-$$-$RANDOM"}
+	isHeader=; [ "$with" = 'header' ] && isHeader=t
 	while IFS=$'\n' read -r dirspec || [ -n "$dirspec" ]
 	do
 	    [ -d "$dirspec" ] || continue
@@ -260,9 +271,7 @@ case "$with" in
 		eval "$betweenCommand" <&3 || { exitStatus=$?; if [ $exitStatus -gt $status ]; then status=$exitStatus; fi; }
 	    fi
 
-	    if [ "$with" = 'header' ]; then
-		header ${isFirst:+--first} "$dirspec"
-	    fi
+	    header="$dirspec"
 
 	    if [ "$isLocalDir" ]; then
 		if [ "$dirspec" != . -a "$dirspec" != "$PWD" ]; then
@@ -280,13 +289,14 @@ case "$with" in
 		[ "${interpolatedCommands[*]}" = "${commands[*]}" ] || f=()
 	    fi
 
-	    reportProgress "$dirspec"
+	    reportProgress "$header"
 	    if [ "$isNeedEval" ]; then
 		typeset -a c=("${interpolatedCommands[@]}" "${f[@]}")
 	    else
 		typeset -a c=('"${interpolatedCommands[@]}" "${f[@]}"')
 	    fi
-	    eval "${c[@]}" <&3 || { exitStatus=$?; if [ $exitStatus -gt $status ]; then status=$exitStatus; fi; }
+	    (eval "${isHeader:+{}" "${c[@]}" "${isHeader:+; \} $errorRedir | withHeader "${colorArg[@]}" --id '$EACHDIR_HEADER_ID' -- '$header'}") <&3 || \
+		{ exitStatus=$?; if [ $exitStatus -gt $status ]; then status=$exitStatus; fi; }
 	    isFirst=
 	done < <(eval '$dirSource "$@"' "${dirProcessor:+|}" "$dirProcessor")
 	exit $status
