each{Arg,Dir,File}: FIX: Actually use runWith if any runWithPrompt args are given
The default $runWithCommand never saw action because $with is only changed by --with-prompt. Do away with a separate $runWithCommand and use $with for the selection as well.
Robustness: Handle with=header via fall-through and assert on unknown $what values.

diff --git a/bin/eachArg b/bin/eachArg
--- a/bin/eachArg
+++ b/bin/eachArg
@@ -66,7 +66,6 @@ with=
 commands=
 betweenCommand=
 usageRedirectCommand=
-runWithCommand=runWith
 typeset -a runWithPromptArgs=()
 while [ $# -ne 0 ]
 do
@@ -91,12 +90,12 @@ do
 	--command|-c)	shift; commands+="${commands:+ ; }$1"; shift;;
 	--progress)	shift; progressSink="$1"; shift;;
 	--with-header)	shift; with=header;;
-	--with-prompt)	shift; with=prompt; runWithCommand=runWithPrompt;;
+	--with-prompt)	shift; with=runWithPrompt;;
 
 	--trailing-prompt|--no-trailing-prompt|--no-output-no-prompt|--no-output-no-error|--no-success-no-count|--exit-on-success|--exit-on-failure|--emulate-prompt|--worst-status)
-			runWithPromptArgs+=("$1"); shift;;
+			runWithPromptArgs+=("$1"); shift; : ${with:=runWith};;
 	--initial-status|--no-count-on|--exit-on|--exit-unless|--comment|--summarize-failed|--summarize-failed-separator)
-			runWithPromptArgs+=("$1" "$2"); shift; shift;;
+			runWithPromptArgs+=("$1" "$2"); shift; shift; : ${with:=runWith};;
 
 	--between-command)
 			shift; betweenCommand="$1"; shift;;
@@ -123,7 +122,7 @@ if [ -z "$commands" ]; then
     echo
     printUsage "$0"
     exit 2
-elif [ ${#runWithPromptArgs[@]} -gt 0 -a "$with" = header ]; then
+elif [ ${#runWithPromptArgs[@]} -gt 0 -a "$with" = 'header' ]; then
     echo 'ERROR: Cannot combine runWith[Prompt] arguments with --with-header.'
     echo
     printUsage "$0"
@@ -154,8 +153,9 @@ fi
 
 
 isFirst=t
+isHeader=
 case "$with" in
-    prompt)
+    runWith*)
 	[ ${#runWithPromptArgs[@]} -eq 0 ] && runWithPromptArgs=(--worst-status)
 	for arg
 	do
@@ -176,9 +176,11 @@ case "$with" in
 	    printf '%s ' "$interpolatedCommands" "${a[@]}"
 	    printf '\n'
 	    isFirst=
-	done | ${runWithCommand:?} "${runWithPromptArgs[@]}"
+	done | ${with:?} "${runWithPromptArgs[@]}"
 	;;
-    *)
+    header)
+	isHeader=t;&
+    '')
 	status=0
 	for arg
 	do
@@ -186,9 +188,7 @@ case "$with" in
 		eval "$betweenCommand" || { exitStatus=$?; if [ $exitStatus -gt $status ]; then status=$exitStatus; fi; }
 	    fi
 
-	    if [ "$with" = 'header' ]; then
-		header ${isFirst:+--first} "$arg"
-	    fi
+	    [ ! "$isHeader" ] || header ${isFirst:+--first} "$arg"
 
 	    typeset -a a=("$arg")   # No quoting, as array provides separation.
 	    printf -v quotedArg '%q' "$arg"
@@ -202,4 +202,5 @@ case "$with" in
 	done
 	exit $status
 	;;
+    *)	printf >&2 'ASSERT: Invalid strategy: %s\n' "$with"; exit 3;;
 esac
diff --git a/bin/eachDir b/bin/eachDir
--- a/bin/eachDir
+++ b/bin/eachDir
@@ -113,7 +113,6 @@ typeset -a colorArg=()
 commands=
 betweenCommand=
 usageRedirectCommand=
-runWithCommand=runWith
 typeset -a runWithPromptArgs=()
 while [ $# -ne 0 ]
 do
@@ -146,12 +145,12 @@ do
 			shift; errorRedir='';;
 	--no-color|--color=*)	colorArg=("$1"); shift;;
 	--color)		colorArg=("$1" "$2"); shift; shift;;
-	--with-prompt)	shift; with=prompt; runWithCommand=runWithPrompt;;
+	--with-prompt)	shift; with=runWithPrompt;;
 
 	--trailing-prompt|--no-trailing-prompt|--no-output-no-prompt|--no-output-no-error|--no-success-no-count|--exit-on-success|--exit-on-failure|--emulate-prompt|--worst-status)
-			runWithPromptArgs+=("$1"); shift;;
+			runWithPromptArgs+=("$1"); shift; : ${with:=runWith};;
 	--initial-status|--no-count-on|--exit-on|--exit-unless|--comment|--summarize-failed|--summarize-failed-separator)
-			runWithPromptArgs+=("$1" "$2"); shift; shift;;
+			runWithPromptArgs+=("$1" "$2"); shift; shift; : ${with:=runWith};;
 
 	--between-command)
 			shift; betweenCommand="$1"; shift;;
@@ -197,7 +196,7 @@ if [ -z "$commands" ]; then
     echo
     printUsage "$0"
     exit 2
-elif [ ${#runWithPromptArgs[@]} -gt 0 -a "$with" = header ]; then
+elif [ ${#runWithPromptArgs[@]} -gt 0 -a "$with" = 'header' ]; then
     echo 'ERROR: Cannot combine runWith[Prompt] arguments with --with-header.'
     echo
     printUsage "$0"
@@ -228,8 +227,9 @@ else
 fi
 
 isFirst=t
+isHeader=
 case "$with" in
-    prompt)
+    runWith*)
 	[ ${#runWithPromptArgs[@]} -eq 0 ] && runWithPromptArgs=(--worst-status)
 	eval '$dirSource "$@"' "${dirProcessor:+|}" "$dirProcessor" | while IFS=$'\n' read -r dirspec || [ -n "$dirspec" ]
 	do
@@ -258,13 +258,14 @@ case "$with" in
 	    printf '%s ' "$interpolatedCommands" "${f[@]}"
 	    printf '\n'
 	    isFirst=
-	done | ${runWithCommand:?} "${runWithPromptArgs[@]}"
+	done | ${with:?} "${runWithPromptArgs[@]}"
 	;;
-    *)
+    header)
+	isHeader=t;&
+    '')
 	status=0
 	exec 3<&0
 	: ${EACHDIR_HEADER_ID:="eachDir-$$-$RANDOM"}
-	isHeader=; [ "$with" = 'header' ] && isHeader=t
 	while IFS=$'\n' read -r dirspec || [ -n "$dirspec" ]
 	do
 	    [ -d "$dirspec" ] || continue
@@ -299,4 +300,5 @@ case "$with" in
 	done < <(eval '$dirSource "$@"' "${dirProcessor:+|}" "$dirProcessor")
 	exit $status
 	;;
+    *)	printf >&2 'ASSERT: Invalid strategy: %s\n' "$with"; exit 3;;
 esac
diff --git a/bin/eachFile b/bin/eachFile
--- a/bin/eachFile
+++ b/bin/eachFile
@@ -114,7 +114,6 @@ typeset -a colorArg=()
 commands=
 betweenCommand=
 usageRedirectCommand=
-runWithCommand=runWith
 typeset -a runWithPromptArgs=()
 while [ $# -ne 0 ]
 do
@@ -147,12 +146,12 @@ do
 			shift; errorRedir='';;
 	--no-color|--color=*)	colorArg=("$1"); shift;;
 	--color)		colorArg=("$1" "$2"); shift; shift;;
-	--with-prompt)	shift; with=prompt; runWithCommand=runWithPrompt;;
+	--with-prompt)	shift; with=runWithPrompt;;
 
 	--trailing-prompt|--no-trailing-prompt|--no-output-no-prompt|--no-output-no-error|--no-success-no-count|--exit-on-success|--exit-on-failure|--emulate-prompt|--worst-status)
-			runWithPromptArgs+=("$1"); shift;;
+			runWithPromptArgs+=("$1"); shift; : ${with:=runWith};;
 	--initial-status|--no-count-on|--exit-on|--exit-unless|--comment|--summarize-failed|--summarize-failed-separator)
-			runWithPromptArgs+=("$1" "$2"); shift; shift;;
+			runWithPromptArgs+=("$1" "$2"); shift; shift; : ${with:=runWith};;
 
 	--between-command)
 			shift; betweenCommand="$1"; shift;;
@@ -198,7 +197,7 @@ if [ -z "$commands" ]; then
     echo
     printUsage "$0"
     exit 2
-elif [ ${#runWithPromptArgs[@]} -gt 0 -a "$with" = header ]; then
+elif [ ${#runWithPromptArgs[@]} -gt 0 -a "$with" = 'header' ]; then
     echo 'ERROR: Cannot combine runWith[Prompt] arguments with --with-header.'
     echo
     printUsage "$0"
@@ -229,8 +228,9 @@ else
 fi
 
 isFirst=t
+isHeader=
 case "$with" in
-    prompt)
+    runWith*)
 	[ ${#runWithPromptArgs[@]} -eq 0 ] && runWithPromptArgs=(--worst-status)
 	eval '$fileSource "$@"' "${fileProcessor:+|}" "$fileProcessor" | while IFS=$'\n' read -r filespec || [ -n "$filespec" ]
 	do
@@ -257,12 +257,13 @@ case "$with" in
 	    printf '%s ' "$interpolatedCommands" "${f[@]}"
 	    printf '\n'
 	    isFirst=
-	done | ${runWithCommand:?} "${runWithPromptArgs[@]}"
+	done | ${with:?} "${runWithPromptArgs[@]}"
 	;;
-    *)
+    header)
+	isHeader=t;&
+    '')
 	status=0
 	: ${EACHFILE_HEADER_ID:="eachFile-$$-$RANDOM"}
-	isHeader=; [ "$with" = 'header' ] && isHeader=t
 	exec 3<&0
 	while IFS=$'\n' read -r filespec || [ -n "$filespec" ]
 	do
@@ -296,4 +297,5 @@ case "$with" in
 	done < <(eval '$fileSource "$@"' "${fileProcessor:+|}" "$fileProcessor")
 	exit $status
 	;;
+    *)	printf >&2 'ASSERT: Invalid strategy: %s\n' "$with"; exit 3;;
 esac
