each{Arg,Dir,File}: ENH: Allow progress reporting via --progress SINK
Powered by my progressNotification command.

diff --git a/bin/eachArg b/bin/eachArg
--- a/bin/eachArg
+++ b/bin/eachArg
@@ -3,11 +3,13 @@
 : ${EACHARG_ARG_MARKER='{}'}
 argMarker="$EACHARG_ARG_MARKER"; unset EACHARG_ARG_MARKER
 
+hasProgressNotification=; type -t progressNotification >/dev/null && hasProgressNotification=t
+
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[--with-header|--with-prompt [--initial-status NUM] [--trailing-prompt|--no-trailing-prompt] [--no-output-no-prompt] [--no-output-no-error] [--emulate-prompt]] [--no-success-no-count|--no-count-on N] [--exit-on-success|--exit-on-failure|--exit-on NUM] [--worst-status] [--comment COMMENT] [--summarize-failed ERROR-TEXT [--summarize-failed-separator SEP]] [--between-command BETWEEN-COMMAND] [--usage-redirect COMMAND] -c|--command "COMMANDLINE" [...] | SIMPLECOMMAND [...] -- ARGUMENT [...] [-?|-h|--help]'
+    printf 'Usage: %q%s %s\n' "$(basename "$1")" "${hasProgressNotification:+ [--progress SINK]}" '[--with-header|--with-prompt [--initial-status NUM] [--trailing-prompt|--no-trailing-prompt] [--no-output-no-prompt] [--no-output-no-error] [--emulate-prompt]] [--no-success-no-count|--no-count-on N] [--exit-on-success|--exit-on-failure|--exit-on NUM] [--worst-status] [--comment COMMENT] [--summarize-failed ERROR-TEXT [--summarize-failed-separator SEP]] [--between-command BETWEEN-COMMAND] [--usage-redirect COMMAND] -c|--command "COMMANDLINE" [...] | SIMPLECOMMAND [...] -- ARGUMENT [...] [-?|-h|--help]'
 }
 printUsage()
 {
@@ -27,8 +29,11 @@ COMMAND per ARGUMENT.
 HELPDESCRIPTION
     echo
     printShortUsage "$1"
+    echo
     cat <<HELPTEXT
-    --with-header   Print a header (containing the current ARGUMENT) before each
+${hasProgressNotification:+    --progress SINK Report the current ARGUMENT through one of the SINKs of the
+		    progressNotification command.
+}    --with-header   Print a header (containing the current ARGUMENT) before each
 		    execution.
     --with-prompt   Emulate a full prompt (as if invoking COMMAND) before each
 		    execution.
@@ -74,6 +79,7 @@ do
     esac
 done
 
+progressSink=
 with=
 typeset -a commands=()
 betweenCommand=
@@ -85,6 +91,7 @@ do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
 	--command|-c)	shift; commands+=(${commands:+;} "$1"); isNeedEval=t; shift;;
+	--progress)	shift; progressSink="$1"; shift;;
 	--with-header)	shift; with=header;;
 	--with-prompt)	shift; with=prompt; runWithCommand=runWithPrompt;;
 
@@ -139,6 +146,18 @@ if [ $# -eq 0 ]; then
     exit 2
 fi
 
+if [ "$hasProgressNotification" ] && [ -n "$progressSink" ]; then
+    exec 4> >(progressNotification --to "$progressSink" --prepend-count 'argument' --count-to $# 2>/dev/null)
+
+    reportProgress()
+    {
+	trap 'reportProgress() { :; }; trap PIPE' PIPE
+	printf '%s\n' "$*" >&4 2>/dev/null  # Silence "printf: write error: Broken pipe"
+    }
+else
+    reportProgress() { :; }
+fi
+
 
 isFirst=t
 case "$with" in
@@ -160,6 +179,7 @@ case "$with" in
 	    typeset -a a=("$arg")   # Quoter for isNeedEval=t is off, so need to use quoted arg here.
 	    [ "${interpolatedCommands[*]}" = "${commands[*]}" ] || a=()
 
+	    reportProgress "$arg"
 	    printf "$quoter " "${interpolatedCommands[@]}" "${a[@]}"
 	    printf '\n'
 	    isFirst=
@@ -182,6 +202,7 @@ case "$with" in
 	    typeset -a interpolatedCommands=("${commands[@]//"$argMarker"/$arg}")
 	    [ "${interpolatedCommands[*]}" = "${commands[*]}" ] || a=()
 
+	    reportProgress "$arg"
 	    if [ "$isNeedEval" ]; then
 		eval "${interpolatedCommands[@]}" '"${a[@]}"'
 	    else
diff --git a/bin/eachDir b/bin/eachDir
--- a/bin/eachDir
+++ b/bin/eachDir
@@ -4,11 +4,13 @@ shopt -qs extglob
 : ${EACHDIR_DIR_MARKER='{}'}
 dirMarker="$EACHDIR_DIR_MARKER"; unset EACHDIR_DIR_MARKER
 
+hasProgressNotification=; type -t progressNotification >/dev/null && hasProgressNotification=t
+
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-l|--local-dir] [--with-header|--with-prompt [--initial-status NUM] [--trailing-prompt|--no-trailing-prompt] [--no-output-no-prompt] [--no-output-no-error] [--emulate-prompt]] [--no-success-no-count|--no-count-on N] [--exit-on-success|--exit-on-failure|--exit-on NUM] [--worst-status] [--comment COMMENT] [--summarize-failed ERROR-TEXT [--summarize-failed-separator SEP]] [--between-command BETWEEN-COMMAND] [--usage-redirect COMMAND] -c|--command "COMMANDLINE" [...] | SIMPLECOMMAND [...] [--] DIR [...] [-?|-h|--help]'
+    printf 'Usage: %q %s%s %s\n' "$(basename "$1")" '[-l|--local-dir]' "${hasProgressNotification:+ [--progress SINK]}" '[--with-header|--with-prompt [--initial-status NUM] [--trailing-prompt|--no-trailing-prompt] [--no-output-no-prompt] [--no-output-no-error] [--emulate-prompt]] [--no-success-no-count|--no-count-on N] [--exit-on-success|--exit-on-failure|--exit-on NUM] [--worst-status] [--comment COMMENT] [--summarize-failed ERROR-TEXT [--summarize-failed-separator SEP]] [--between-command BETWEEN-COMMAND] [--usage-redirect COMMAND] -c|--command "COMMANDLINE" [...] | SIMPLECOMMAND [...] [--] DIR [...] [-?|-h|--help]'
     echo
     printf 'Usage: %q %s\n' "$(basename "$1")" '[...] -c|--command "COMMANDLINE" [...] | SIMPLECOMMAND [...] -f|--find FIND-ARGS ...'
 }
@@ -33,7 +35,9 @@ HELPDESCRIPTION
     cat <<HELPTEXT
     --local-dir|-l  Change the directory to the current DIR before executing
 		    COMMAND; nothing is appended to COMMAND then${dirMarker:+ (but $dirMarker is
-		    still replaced)}.
+		    still replaced)}.${hasProgressNotification:+
+    --progress SINK Report the current DIR through one of the SINKs of the
+	    progressNotification command.}
     --with-header   Print a header (containing the current DIR) before each
 		    execution.
     --with-prompt   Emulate a full prompt (as if invoking COMMAND) before each
@@ -88,6 +92,8 @@ do
 done
 
 isLocalDir=
+progressSink=
+isFixedNumberOfDirs=t
 dirSource='printf %s\n'
 dirProcessor=
 finder()
@@ -115,8 +121,9 @@ do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
 	--local-dir|-l)	shift; isLocalDir=t; dirProcessor='makeAbsolute';;
-	--find|-f)	shift; findArgs=("$@"); set --; dirSource='finder'; break;;
+	--find|-f)	shift; findArgs=("$@"); set --; dirSource='finder'; isFixedNumberOfDirs=; break;;
 	--command|-c)	shift; commands+=(${commands:+;} "$1"); isNeedEval=t; shift;;
+	--progress)	shift; progressSink="$1"; shift;;
 	--with-header)	shift; with=header;;
 	--with-prompt)	shift; with=prompt; runWithCommand=runWithPrompt;;
 
@@ -190,6 +197,19 @@ if [ $# -eq 0 -a ${#findArgs[@]} -eq 0 ]; then
     exit 2
 fi
 
+if [ "$hasProgressNotification" ] && [ -n "$progressSink" ]; then
+    typeset progressCountToArgs=(--count-to $#); [ "$isFixedNumberOfDirs" ] || progressCountToArgs=()
+    exec 4> >(progressNotification --to "$progressSink" --prepend-count 'dir' "${progressCountToArgs[@]}" 2>/dev/null)
+
+    reportProgress()
+    {
+	trap 'reportProgress() { :; }; trap PIPE' PIPE
+	printf '%s\n' "$*" >&4 2>/dev/null  # Silence "printf: write error: Broken pipe"
+    }
+else
+    reportProgress() { :; }
+fi
+
 isFirst=t
 dirspec=.
 case "$with" in
@@ -218,7 +238,7 @@ case "$with" in
 		[ "${interpolatedCommands[*]}" = "${commands[*]}" ] || f=()
 	    fi
 
-
+	    reportProgress "$dirspec"
 	    printf "$quoter " "${interpolatedCommands[@]}" "${f[@]}"
 	    printf '\n'
 	    isFirst=
@@ -253,6 +273,7 @@ case "$with" in
 		[ "${interpolatedCommands[*]}" = "${commands[*]}" ] || f=()
 	    fi
 
+	    reportProgress "$dirspec"
 	    if [ "$isNeedEval" ]; then
 		eval "${interpolatedCommands[@]}" '"${f[@]}"'
 	    else
diff --git a/bin/eachFile b/bin/eachFile
--- a/bin/eachFile
+++ b/bin/eachFile
@@ -4,11 +4,13 @@ shopt -qs extglob
 : ${EACHFILE_FILE_MARKER='{}'}
 fileMarker="$EACHFILE_FILE_MARKER"; unset EACHFILE_FILE_MARKER
 
+hasProgressNotification=; type -t progressNotification >/dev/null && hasProgressNotification=t
+
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-l|--local-dir] [--with-header|--with-prompt [--initial-status NUM] [--trailing-prompt|--no-trailing-prompt] [--no-output-no-prompt] [--no-output-no-error] [--emulate-prompt]] [--no-success-no-count|--no-count-on N] [--exit-on-success|--exit-on-failure|--exit-on NUM] [--worst-status] [--comment COMMENT] [--summarize-failed ERROR-TEXT [--summarize-failed-separator SEP]] [--between-command BETWEEN-COMMAND] [--usage-redirect COMMAND] -c|--command "COMMANDLINE" [...] | SIMPLECOMMAND [...] [--] FILE [...] [-?|-h|--help]'
+    printf 'Usage: %q %s%s %s\n' "$(basename "$1")" '[-l|--local-dir]' "${hasProgressNotification:+ [--progress SINK]}" '[--with-header|--with-prompt [--initial-status NUM] [--trailing-prompt|--no-trailing-prompt] [--no-output-no-prompt] [--no-output-no-error] [--emulate-prompt]] [--no-success-no-count|--no-count-on N] [--exit-on-success|--exit-on-failure|--exit-on NUM] [--worst-status] [--comment COMMENT] [--summarize-failed ERROR-TEXT [--summarize-failed-separator SEP]] [--between-command BETWEEN-COMMAND] [--usage-redirect COMMAND] -c|--command "COMMANDLINE" [...] | SIMPLECOMMAND [...] [--] FILE [...] [-?|-h|--help]'
     echo
     printf 'Usage: %q %s\n' "$(basename "$1")" '[...] -c|--command "COMMANDLINE" [...] | SIMPLECOMMAND [...] -f|--find FIND-ARGS ...'
 }
@@ -32,7 +34,9 @@ HELPDESCRIPTION
     echo
     cat <<HELPTEXT
     --local-dir|-l  Change the directory to the one containing the current FILE
-		    before executing COMMAND, and only pass the filename itself.
+		    before executing COMMAND, and only pass the filename itself.${hasProgressNotification:+
+    --progress SINK Report the current FILE through one of the SINKs of the
+		    progressNotification command.}
     --with-header   Print a header (containing the current FILE) before each
 		    execution.
     --with-prompt   Emulate a full prompt (as if invoking COMMAND) before each
@@ -89,6 +93,8 @@ do
 done
 
 isLocalDir=
+progressSink=
+isFixedNumberOfFiles=t
 fileSource='printf %s\n'
 fileProcessor=
 finder()
@@ -116,8 +122,9 @@ do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
 	--local-dir|-l)	shift; isLocalDir=t; fileProcessor='makeAbsolute';;
-	--find|-f)	shift; findArgs=("$@"); set --; fileSource='finder'; break;;
+	--find|-f)	shift; findArgs=("$@"); set --; fileSource='finder'; isFixedNumberOfFiles=; break;;
 	--command|-c)	shift; commands+=(${commands:+;} "$1"); isNeedEval=t; shift;;
+	--progress)	shift; progressSink="$1"; shift;;
 	--with-header)	shift; with=header;;
 	--with-prompt)	shift; with=prompt; runWithCommand=runWithPrompt;;
 
@@ -191,6 +198,19 @@ if [ $# -eq 0 -a ${#findArgs[@]} -eq 0 ]; then
     exit 2
 fi
 
+if [ "$hasProgressNotification" ] && [ -n "$progressSink" ]; then
+    typeset progressCountToArgs=(--count-to $#); [ "$isFixedNumberOfFiles" ] || progressCountToArgs=()
+    exec 4> >(progressNotification --to "$progressSink" --prepend-count 'file' "${progressCountToArgs[@]}" 2>/dev/null)
+
+    reportProgress()
+    {
+	trap 'reportProgress() { :; }; trap PIPE' PIPE
+	printf '%s\n' "$*" >&4 2>/dev/null  # Silence "printf: write error: Broken pipe"
+    }
+else
+    reportProgress() { :; }
+fi
+
 isFirst=t
 dirspec=.
 case "$with" in
@@ -218,6 +238,7 @@ case "$with" in
 	    typeset -a f=("$filespec")	# Quoter for isNeedEval=t is off, so need to use quoted arg here.
 	    [ "${interpolatedCommands[*]}" = "${commands[*]}" ] || f=()
 
+	    reportProgress "$filespec"
 	    printf "$quoter " "${interpolatedCommands[@]}" "${f[@]}"
 	    printf '\n'
 	    isFirst=
@@ -252,6 +273,7 @@ case "$with" in
 	    typeset -a interpolatedCommands=("${commands[@]//"$fileMarker"/$filespec}")
 	    [ "${interpolatedCommands[*]}" = "${commands[*]}" ] || f=()
 
+	    reportProgress "$filespec"
 	    if [ "$isNeedEval" ]; then
 		eval "${interpolatedCommands[@]}" '"${f[@]}"'
 	    else
