each*: Refactoring: Replace hard-coded runWithPrompt command-line argument parse with delegation
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/eachArg b/bin/eachArg
--- a/bin/eachArg
+++ b/bin/eachArg
@@ -147,20 +147,26 @@ do
 	--no-color|--color=*)	colorArg=("$1"); shift;;
 	--color)		colorArg=("$1" "$2"); shift; shift;;
 	--with-prompt)	shift; with=runWithPrompt;;
-
-	--trailing-prompt|--no-trailing-prompt|--no-output-no-prompt|--no-output-no-error|--no-success-no-count|--exit-on-success|--exit-on-failure|--emulate-prompt|--worst-status)
-			runWithPromptArgs+=("$1"); shift; : ${with:=runWith};;
-	--initial-status|--no-count-on|--exit-on|--exit-unless|--comment|--summarize-failed|--summarize-failed-separator)
-			runWithPromptArgs+=("$1" "$2"); shift; shift; : ${with:=runWith};;
-	--status-99-is-noop)
-			runWithPromptArgs+=("$1"); shift; additionalSuccessStatus=99;;
-
 	--between-command)
 			shift; betweenCommand="$1"; shift;;
 	--usage-redirect)
 			shift; usageRedirectCommand="$1"; shift;;
+
+	--status-99-is-noop)
+			runWithPromptArgs+=("$1"); shift; additionalSuccessStatus=99;;
 	--)		shift; parseTail "$@"; shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	-*)		if argCount=$(runWithPrompt --understands "$@"); then
+			    while ((argCount-- > 0))
+			    do
+				runWithPromptArgs+=("$1"); shift
+			    done
+			    : ${with:=runWith}
+			elif [ $? -eq 2 ]; then
+			    exit 2
+			else
+			    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2
+			fi
+			;;
 	*)		parseTail "$@"; break;;
     esac
 done
