WIP: CHG: Pass above|below to --section-info-include-separator
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/eachSection b/bin/eachSection
--- a/bin/eachSection
+++ b/bin/eachSection
@@ -24,17 +24,19 @@ printUsage()
     --elide-empty-files|-z\
 			Empty sections do not produce empty files.' \
 	-e '/^ *--section-modifier-command/i\
-    --section-info-include-separator\
-			Pass the separator line to the section info extractor\
-			(not just the section contents).' \
+    --section-info-include-separator above|below\
+			Pass the separator line (which belongs to the section\
+			above / below) to the section info extractor (not just\
+			the section contents).' \
 	-e '/^ *--splitter/b removeOptionLoop' \
-	-e '/^Usage:$/N' -e '/\(^\|\n\)Usage: */{ s/\(^\|\n\)\(Usage: *\)\?\(\([^ |]\+ \)*\(| \)\?\)eachSplit /\1\2\3'"$(basename "$1")"' /; s/\[--splitter SPLIT-COMMAND OPTIONS FILE PREFIX ARGS ;\] //;  s/\[--section-modifier-command/[--section-info-include-separator] &/; }' \
+	-e '/^Usage:$/N' -e '/\(^\|\n\)Usage: */{ s/\(^\|\n\)\(Usage: *\)\?\(\([^ |]\+ \)*\(| \)\?\)eachSplit /\1\2\3'"$(basename "$1")"' /; s/\[--splitter SPLIT-COMMAND OPTIONS FILE PREFIX ARGS ;\] //;  s/\[--section-modifier-command/[--section-info-include-separator above|below] &/; }' \
 	-e '/^Example:$/N' -e '/\(^\|\n\)Example: */{ s/\(^\|\n\)\(Example: *\)\?eachSplit /\1\2'"$(basename "$1") /; }" \
 	-e b -e :removeFirstParagraphLoop -e '{ /\(^\|\n\)$/{ s/^\(.*\n\)\?//; b; }; N; b removeFirstParagraphLoop; }' \
 	-e b -e :removeOptionLoop -e '{ /\n *--splitter[^\n]*$/{ N; b removeOptionLoop; }; /\n *--[^\n]*$\|\n[^	 ]\|\n$/{ s/^\(.*\n\)\?//; b; }; N; b removeOptionLoop; }'
 }
 
 separatorPattern='^-\{2,3\}$'
+isSeparatorBelow=
 typeset -a suppressedMatchedArg=(--suppress-matched)
 typeset -a args=()
 while [ $# -ne 0 ]
@@ -45,6 +47,15 @@ do
 			shift; separatorPattern="${1:?}"; shift;;
 	--section-info-include-separator)
 			shift
+			case "${1:?}" in
+			    above)  ;;
+			    below)  isSeparatorBelow=t;;
+			    *)	    echo >&2 'ERROR: --section-info-include-separator supports only "above" or "below".'
+				    echo >&2
+				    printUsage "$0" >&2
+				    exit 2
+				    ;;
+			esac; shift
 			suppressedMatchedArg=()
 			args+=(--piece-modifier-exec sed -i "/${separatorPattern//\//\\/}/d" -- "${EACHSPLIT_MODIFIER_MARKER:-{\}}" "${EACHSPLIT_MODIFIER_END:-;}")
 			;;
@@ -55,4 +66,4 @@ do
 done
 
 EACHSPLIT_FILE_PREFIX="$EACHSECTION_FILE_PREFIX" \
-    exec eachSplit --splitter csplit --quiet "${suppressedMatchedArg[@]}" --prefix=PREFIX OPTIONS FILE ARGS \; "/${separatorPattern}/" '{*}' "${args[@]}" "$@"
+    exec eachSplit --splitter csplit --quiet "${suppressedMatchedArg[@]}" --prefix=PREFIX OPTIONS FILE ARGS \; "/${separatorPattern}/${isSeparatorBelow:++1}" '{*}' "${args[@]}" "$@"
