eachArg: CHG: Allow no passed arguments, indicate no args with (configurable) exit status 99 (cp. 2f4d5a8, 717c165, 125bed6)
(This relates to commit 2f4d5a89a3c8deffc427d41175822cedb606159e, 717c1650222d29586485a2995d34ebca9ebb36cd and 125bed61e24e3b0b95d1cf925cb8c47b35896e08)

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/eachArg b/bin/eachArg
--- a/bin/eachArg
+++ b/bin/eachArg
@@ -1,6 +1,7 @@
 #!/bin/bash
 set -o pipefail
 
+: ${EACHARG_NO_ARG_EXIT_STATUS:=99}
 : ${EACHARG_COMMAND_JOINER=;}
 : ${EACHARG_EXEC_END=;}
 : ${EACHARG_ARGUMENTS_END=;}
@@ -15,11 +16,11 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q%s %s\n' "$(basename "$1")" "${hasProgressNotification:+ [--progress SINK]}" "[--with-header [--separate-errors] [--color=(always|auto|never)|--no-color]|--with-prompt $(runWithPrompt --get-short-usage 2>/dev/null)] [--between-command BETWEEN-COMMAND] [--usage-redirect COMMAND] -c|--command \"COMMANDLINE\" [...] --exec SIMPLECOMMAND [...] ${EACHARG_EXEC_END} [--exec ...] | ([--] SIMPLECOMMAND [...] --) ARGUMENT [...] [-?|-h|--help]"
+    printf 'Usage: %q%s %s\n' "$(basename "$1")" "${hasProgressNotification:+ [--progress SINK]}" "[--with-header [--separate-errors] [--color=(always|auto|never)|--no-color]|--with-prompt $(runWithPrompt --get-short-usage 2>/dev/null)] [--between-command BETWEEN-COMMAND] [--usage-redirect COMMAND] -c|--command \"COMMANDLINE\" [...] --exec SIMPLECOMMAND [...] ${EACHARG_EXEC_END} [--exec ...] | ([--] SIMPLECOMMAND [...] --) [ARGUMENT ...] [-?|-h|--help]"
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" "[...] -m|--trailing-argument-match-command ARGUMENT-MATCH-COMMANDLINE|-M|--trailing-argument-match-exec ARGUMENT-MATCH-SIMPLECOMMAND [...] ${EACHARG_EXEC_END} [-m|-M ...] -c|--command \"COMMANDLINE\" [-c ...] | --exec SIMPLECOMMAND [...] ${EACHFILE_EXEC_END} [--exec ...] | [--] SIMPLECOMMAND [...] ARGUMENT [...]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "[...] -m|--trailing-argument-match-command ARGUMENT-MATCH-COMMANDLINE|-M|--trailing-argument-match-exec ARGUMENT-MATCH-SIMPLECOMMAND [...] ${EACHARG_EXEC_END} [-m|-M ...] -c|--command \"COMMANDLINE\" [-c ...] | --exec SIMPLECOMMAND [...] ${EACHFILE_EXEC_END} [--exec ...] | [--] SIMPLECOMMAND [...] [ARGUMENT ...]"
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" "[...] --arguments ARG [...] ${EACHARG_ARGUMENTS_END} -c|--command \"COMMANDLINE\" [-c ...] | --exec SIMPLECOMMAND [...] ${EACHFILE_EXEC_END} [--exec ...] | [--] SIMPLECOMMAND [...]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "[...] --arguments [ARG ...] ${EACHARG_ARGUMENTS_END} -c|--command \"COMMANDLINE\" [-c ...] | --exec SIMPLECOMMAND [...] ${EACHFILE_EXEC_END} [--exec ...] | [--] SIMPLECOMMAND [...]"
 }
 printUsage()
 {
@@ -85,6 +86,7 @@ HELPTEXT
 EXIT STATUS:
 Overall exit status is the highest status of all. If you specify any
 runWith[Prompt] argument, --worst-status needs to be explicitly passed.
+    $EACHARG_NO_ARG_EXIT_STATUS	No arguments were passed / accepted.
 
 Example:
 HELPTEXT
@@ -93,6 +95,7 @@ HELPTEXT
 
 progressSink=
 trailingArgumentMatchCommand=
+hadArg=
 typeset -a arguments=()
 with=
 errorRedir='2>&1'
@@ -142,7 +145,10 @@ parseTail()
 	    shift
 	done
 	commands+="${commands:+ $EACHARG_COMMAND_JOINER }${cmd}"
-	[ "$1" = -- ] && shift
+	if [ "$1" = -- ]; then
+	    shift
+	    hadArg=t
+	fi
     fi
 
     arguments+=("$@")
@@ -152,7 +158,7 @@ do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
 	--trailing-argument-match-command|-m)
-			shift; trailingArgumentMatchCommand+="${trailingArgumentMatchCommand:+ ; }${1?}"; shift;;
+			shift; trailingArgumentMatchCommand+="${trailingArgumentMatchCommand:+ ; }${1?}"; shift; hadArg=t;;
 	--trailing-argument-match-exec|-M)
 			shift
 			cmd=
@@ -168,6 +174,7 @@ do
 			fi >&2
 			shift
 			trailingArgumentMatchCommand+="${trailingArgumentMatchCommand:+ ; }${cmd}"
+			hadArg=t
 			;;
 	--arguments)	shift
 			while [ $# -gt 0 -a "$1" != "$EACHARG_ARGUMENTS_END" ]
@@ -180,10 +187,7 @@ do
 			    exit 2
 			fi >&2
 			shift
-			if [ ${#arguments[@]} -eq 0 ]; then
-			    echo 'ERROR: --arguments must be followed by at least one ARGUMENT.'; echo; printUsage "$0"
-			    exit 2
-			fi >&2
+			hadArg=t
 			;;
 	--command|-c)	shift; commands+="${commands:+ $EACHARG_COMMAND_JOINER }$1"; shift;;
 	--exec)		shift
@@ -217,7 +221,7 @@ do
 			commonArgs+=("$1"); shift; isSingleSuccess=t;;
 	--status-99-is-noop)
 			commonArgs+=("$1"); shift; additionalSuccessStatus=99;;
-	--)		shift; parseTail "$@"; set --; break;;
+	--)		shift; hadArg=t; parseTail "$@"; set --; break;;
 	-*)		if argCount=$(runWithPrompt --understands "$@"); then
 			    runWithPromptArgs+=("${@:1:argCount}")
 			    shift $argCount
@@ -243,6 +247,8 @@ elif [ ${#runWithPromptArgs[@]} -gt 0 -a "$with" = 'header' ]; then
     exit 2
 fi >&2
 if [ ${#arguments[@]} -eq 0 ]; then
+    [ ! "$hadArg" ] || exit $EACHDIR_NO_ARG_EXIT_STATUS
+
     echo >&2 'ERROR: No ARGUMENT(s) passed.'
     echo >&2
     if [ "$usageRedirectCommand" ]; then
@@ -295,7 +301,10 @@ case "$with" in
 		printf '\n'
 		isFirst=
 	    done
-	} | ${with:?} "${commonArgs[@]}" "${runWithPromptArgs[@]}"
+	} | \
+	    RUNWITHPROMPT_NO_COMMAND_EXIT_STATUS=$EACHARG_NO_ARG_EXIT_STATUS \
+	    RUNWITH_NO_COMMAND_EXIT_STATUS=$EACHARG_NO_ARG_EXIT_STATUS \
+		${with:?} "${commonArgs[@]}" "${runWithPromptArgs[@]}"
 	;;
     header)
 	isHeader=t;&
@@ -337,7 +346,7 @@ case "$with" in
 	    fi
 	    isFirst=
 	done
-	exit ${singleSuccessStatus:-${status:-${additionalSuccessStatus:-0}}}
+	exit ${singleSuccessStatus:-${status:-${additionalSuccessStatus:-$EACHARG_NO_ARG_EXIT_STATUS}}}
 	;;
     *)	printf >&2 'ASSERT: Invalid strategy: %s\n' "$with"; exit 3;;
 esac
