Refactoring: Replace timeToSeconds() with durationToSeconds invocation
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/filterTimespan b/bin/filterTimespan
--- a/bin/filterTimespan
+++ b/bin/filterTimespan
@@ -16,13 +16,12 @@ printUsage()
 }
 printLongUsage()
 {
+    local timespanFormat="$(DURATIONTOSECONDS_ACCEPT_SIGN=t durationToSeconds --get-short-usage format 2>/dev/null)"
     # This is the long "man page" when launched with the help argument.
     # It is printed to stdout to allow paging with 'more'.
     cat <<HELPDESCRIPTION
 Only print lines where the [+-]SECONDS timespan in the first column is longer /
 shorter than [+-]TIMESPAN.
-SUFFIX may be 's' for seconds (the default), 'm' for minutes, 'h' for hours, 'd'
-for days, 'w' for weeks, 'mo' for months, 'y' for years, 'g' for generations.
 HELPDESCRIPTION
     echo
     printShortUsage "$1"
@@ -34,7 +33,7 @@ HELPDESCRIPTION
 			regular expression.
     --keep-timespan|-k	Keep the timespan column. By default, the column is
 			dropped.
-    --shorter|--longer|-lt|-le|-eq|-ne|-ge|-gt TIMESPAN[SUFFIX]
+    --shorter|--longer|-lt|-le|-eq|-ne|-ge|-gt ${timespanFormat:-TIMESPAN}
 			Compare the timespan in the first column with TIMESPAN
 			(purely mathematically).
 EXIT STATUS:
@@ -43,26 +42,6 @@ EXIT STATUS:
     2	Bad invocation, wrong or missing command-line arguments.
     4	Some line(s) did not contain a valid timespan.
 HELPTEXT
-}
-
-timeToSeconds()
-{
-    [[ "$1" =~ ^([+-])?(.*)$ ]]
-    local sign="${BASH_REMATCH[1]}"
-    local time="${BASH_REMATCH[2]}"
-
-    case "$time" in
-	+([0-9])?(s))   age="${time%s}";;
-	+([0-9])m)	age=$((${time%m} * 60));;
-	+([0-9])h)	age=$((${time%h} * 3600));;
-	+([0-9])d)	age=$((${time%d} * 86400));;
-	+([0-9])w)	age=$((${time%w} * 86400 * 7));;
-	+([0-9])mo)	age=$((${time%mo} * 86400 * 30));;
-	+([0-9])y)	age=$((${time%y} * 86400 * 365));;
-	+([0-9])g)	age=$((${time%g} * 86400 * 9131));;
-	*)		printf >&2 'ERROR: Illegal age: %s\n' "$1"; exit 2;;
-    esac
-    printf %s%s "$sign" "$age"
 }
 
 isKeepTimespan=
@@ -75,10 +54,10 @@ do
 			shift; IFS="$1"; shift;;
 	--keep-timespan|-k)
 			shift; isKeepTimespan=t;;
-	--shorter)	shift; age="$(timeToSeconds "$1")" || exit $?; shift; compareOp=-lt;;
-	--longer)	shift; age="$(timeToSeconds "$1")" || exit $?; shift; compareOp=-gt;;
+	--shorter)	shift; age=$(DURATIONTOSECONDS_ACCEPT_SIGN=t durationToSeconds -- "${1:?}") || { printf >&2 'ERROR: Illegal TIMESPAN: %s\n' "$1"; exit 2; }; shift; compareOp=-lt;;
+	--longer)	shift; age=$(DURATIONTOSECONDS_ACCEPT_SIGN=t durationToSeconds -- "${1:?}") || { printf >&2 'ERROR: Illegal TIMESPAN: %s\n' "$1"; exit 2; }; shift; compareOp=-gt;;
 	-lt|-le|-eq|-ne|-ge|-gt)
-			compareOp="$1"; shift; age="$(timeToSeconds "$1")" || exit $?; shift;;
+			compareOp="$1"; shift; age=$(DURATIONTOSECONDS_ACCEPT_SIGN=t durationToSeconds -- "${1:?}") || { printf >&2 'ERROR: Illegal TIMESPAN: %s\n' "$1"; exit 2; }; shift;;
 	--)		shift; break;;
 	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
diff --git a/bin/onfile b/bin/onfile
--- a/bin/onfile
+++ b/bin/onfile
@@ -21,7 +21,7 @@ STABILIZED_TIME=2147483647
 
 printShortUsage()
 {
-    printf 'Usage: %q %s\n' "$(basename "$1")" "-d|--dir DIR|-g|--glob 'FILE-GLOB' [-d|--dir DIR]|--source-command SOURCE-COMMAND [-d|--dir DIR] [--accept-existing] [-n|--count N|-1] [--delay NUMBER[SUFFIX]] [--stabilization-time NUMBER[SUFFIX]] [-i|--interval NUMBER[SUFFIX] [-l|--max-files N] [-D|--stop-on-empty-dir] [-S|--stop-on-empty-file [--delete-empty-file]] [-s|--stop-on-filename PATTERN] [-t|--stop-after TIMEOUT[SUFFIX]] --print] [[--bare|[--no-capture-output $(runWithPrompt --get-short-usage 2>/dev/null)] [--prefix-command PC] [--prefix-command-command PCC] [--parallel [--parallel-limit N] [--rate-limit NUMBER[SUFFIX]]] [--delete-on-success|--delete-on-failure|--delete-on NUM|--delete-unless NUM] -c|--command \"COMMANDLINE\" | [--] SIMPLECOMMAND [...]] [-?|-h|--help]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "-d|--dir DIR|-g|--glob 'FILE-GLOB' [-d|--dir DIR]|--source-command SOURCE-COMMAND [-d|--dir DIR] [--accept-existing] [-n|--count N|-1] [--delay NUMBER[SUFFIX]] [--stabilization-time TIMESPAN] [-i|--interval NUMBER[SUFFIX] [-l|--max-files N] [-D|--stop-on-empty-dir] [-S|--stop-on-empty-file [--delete-empty-file]] [-s|--stop-on-filename PATTERN] [-t|--stop-after TIMESPAN] --print] [[--bare|[--no-capture-output $(runWithPrompt --get-short-usage 2>/dev/null)] [--prefix-command PC] [--prefix-command-command PCC] [--parallel [--parallel-limit N] [--rate-limit NUMBER[SUFFIX]]] [--delete-on-success|--delete-on-failure|--delete-on NUM|--delete-unless NUM] -c|--command \"COMMANDLINE\" | [--] SIMPLECOMMAND [...]] [-?|-h|--help]"
 }
 printUsage()
 {
@@ -59,6 +59,7 @@ HELPDESCRIPTION
 			the COMMAND.
 HELPTEXT
     runWithPrompt --get-long-usage 2>/dev/null
+    local timespanFormat="$(durationToSeconds --get-short-usage format 2>/dev/null)"
     cat <<HELPTEXT
     --no-capture-output	By default, no status line is printed if the COMMAND did
 			not have any output, and failing parallel invocations
@@ -88,10 +89,10 @@ HELPTEXT
     --delay NUMBER[SUFFIX]
 			Sleep for NUMBER[SUFFIX]] before executing COMMAND (to
 			allow the file to stabilize, for example).
-    --stabilization-time NUMBER[SUFFIX]
-			Wait until NUMBER[SUFFIX] has passed (with a granularity
-			of INTERVAL) after the last modification of the file
-			before recognizing the change.
+    --stabilization-time ${timespanFormat:-TIMESPAN}
+			Wait until TIMESPAN has passed (with a granularity of
+			INTERVAL) after the last modification of the file before
+			recognizing the change.
     --interval|-i INTERVAL[SUFFIX]
 			Wait for INTERVAL seconds between observations of DIR.
 			By default, any change is observed almost immediately.
@@ -108,9 +109,8 @@ HELPTEXT
 			Stop observing if an added filename matches
 			PATTERN. PATTERN is a Bash-style extended regular
 			expression.
-    --stop-after|-t TIMEOUT[SUFFIX]
-			Stop observing if no files have been added for
-			TIMEOUT[SUFFIX].
+    --stop-after|-t ${timespanFormat:-TIMESPAN}
+			Stop observing if no files have been added for TIMEOUT.
     --parallel		Instead of waiting for one COMMAND to finish before
 			executing the next, run each one the moment the change
 			is triggered. The default is sequential invocation.
@@ -136,18 +136,6 @@ SUFFIX may be 's' for seconds (the default), 'm' for minutes, 'h' for hours or
 Example:
 HELPTEXT
     printf '%q %s\n' "$(basename "$1")" "--glob '*.url' -i 5 --accept-existing --delete-on-success --stop-on-empty-file --delete-empty-file -- wget --input-file $fileMarker"
-}
-
-timeToSeconds()
-{
-    case "$1" in
-	+([0-9])?(s))   time="${1%s}";;
-	+([0-9])m)	time=$((${1%m} * 60));;
-	+([0-9])h)	time=$((${1%h} * 3600));;
-	+([0-9])d)	time=$((${1%d} * 86400));;
-	*)		printf >&2 "ERROR: Illegal ${2:-timeout}: %s\\n" "$1"; exit 2;;
-    esac
-    printf %s "$time"
 }
 
 dir=
@@ -216,7 +204,7 @@ do
 	--prefix-command-command)
 				shift; prefixCommandCommand="$1"; shift;;
 	--delay)		shift; delay="$1"; shift;;
-	--stabilization-time)	shift; stabilizationTime="$(timeToSeconds "$1" number)" || exit $?; shift
+	--stabilization-time)	shift; stabilizationTime=$(durationToSeconds -- "${1:?}") || { printf >&2 'ERROR: Illegal TIMESPAN: %s\n' "$1"; exit 2; }; shift
 				SECONDS=$(date +%s) # Need to sync up only once; Bash will keep the epoch updated from then on.
 				;;
 	--interval|-i)		shift; interval="$1"; shift;;
@@ -224,7 +212,7 @@ do
 	--stop-on-empty-dir|-D)	shift; isStopOnEmptyDir=t;;
 	--stop-on-empty-file|-S)
 				shift; isStopOnEmptyFile=t;;
-	--stop-after|-t)	shift; stopAfter="$(timeToSeconds "$1")" || exit $?; shift;;
+	--stop-after|-t)	shift; stopAfter=$(durationToSeconds -- "${1:?}") || { printf >&2 'ERROR: Illegal TIMESPAN: %s\n' "$1"; exit 2; }; shift;;
 	--delete-empty-file)	shift; isDeleteEmptyFile=t;;
 	--stop-on-filename|-s)	shift; stopFilenamePattern="$1"; shift;;
 	--parallel-limit)	shift; parallelLimit="$1"; shift;;
diff --git a/bin/slowcommand b/bin/slowcommand
--- a/bin/slowcommand
+++ b/bin/slowcommand
@@ -7,7 +7,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" 'NUMBER[SUFFIX] [-b|--before NUMBER[SUFFIX]] -c|--command "COMMANDLINE" [-c ...] | [--] SIMPLECOMMAND [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" 'TIMESPAN [-b|--before TIMESPAN] -c|--command "COMMANDLINE" [-c ...] | [--] SIMPLECOMMAND [...] [-?|-h|--help]'
 }
 printUsage()
 {
@@ -21,43 +21,33 @@ printLongUsage()
     # This is the long "man page" when launched with the help argument.
     # It is printed to stdout to allow paging with 'more'.
     cat <<HELPDESCRIPTION
-Execute COMMAND and make it last at least NUMBER[SUFFIX], sleeping some more if
+Execute COMMAND and make it last at least TIMESPAN, sleeping some more if
 necessary.
 HELPDESCRIPTION
     echo
     printShortUsage "$1"
     echo
+    local timespanFormat="$(durationToSeconds --get-short-usage format 2>/dev/null)"
     cat <<HELPTEXT
-    --before|-b NUMBER[SUFFIX]
-			Sleep NUMBER[SUFFIX] before invoking COMMAND. This
-			already counts towards the entire runtime.
+    --before|-b ${timespanFormat:-TIMESPAN}
+			Sleep TIMESPAN before invoking COMMAND. This already
+			counts towards the entire runtime.
 HELPTEXT
 }
 
-timeToSeconds()
-{
-    case "$1" in
-	+([0-9])?(s))   time="${1%s}";;
-	+([0-9])m)	time=$((${1%m} * 60));;
-	+([0-9])h)	time=$((${1%h} * 3600));;
-	+([0-9])d)	time=$((${1%d} * 86400));;
-	*)		printf >&2 'ERROR: Illegal duration: %s\n' "$1"; exit 2;;
-    esac
-    printf %s "$time"
-}
 case "$1" in
     --help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
-    '')			echo >&2 'ERROR: No duration (NUMBER[SUFFIX]) passed.'; echo >&2; printUsage "$0" >&2; exit 2;;
+    '')			echo >&2 'ERROR: No TIMESPAN passed.'; echo >&2; printUsage "$0" >&2; exit 2;;
 esac
 
-duration="$(timeToSeconds "$1")" || exit $?; shift
+duration=$(durationToSeconds -- "${1:?}") || { printf >&2 'ERROR: Illegal TIMESPAN: %s\n' "$1"; exit 2; }
 before=
 commands=
 while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-	--before|-b)	shift; before="$(timeToSeconds "$1")" || exit $?; shift;;
+	--before|-b)	shift; before=$(durationToSeconds -- "${1:?}") || { printf >&2 'ERROR: Illegal TIMESPAN: %s\n' "$1"; exit 2; }; shift;;
 	--command|-c)	shift; commands+="${commands:+ $SLOWCOMMAND_COMMAND_JOINER }$1"; shift;;
 	--)		shift; break;;
 	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
