onfile: Refactoring: Replace hard-coded runWithPrompt command-line argument parse with delegation
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/onfile b/bin/onfile
--- a/bin/onfile
+++ b/bin/onfile
@@ -201,10 +201,6 @@ do
 	--parallel)		shift; isParallel=t;;
 	--print)		shift; isPrint=t;;
 	--bare)			shift; isBare=t; runWithCommand=runWith;;
-	--trailing-prompt|--no-trailing-prompt|--no-output-no-prompt|--no-output-no-error|--no-success-no-count|--emulate-prompt|--worst-status|--status-99-is-noop)
-				runWithPromptArgs+=("$1"); shift;;
-	--initial-status|--no-count-on|--comment|--summarize-failed|--summarize-failed-separator)
-				runWithPromptArgs+=("$1" "$2"); shift; shift;;
 	--no-capture-output)	shift; isCaptureOutput=;;
 	--command|-c)		shift
 				if [ -n "$prefixCommandCommand" ]; then
@@ -233,9 +229,19 @@ do
 	--stop-on-filename|-s)	shift; stopFilenamePattern="$1"; shift;;
 	--parallel-limit)	shift; parallelLimit="$1"; shift;;
 	--rate-limit)		shift; rateLimit="$1"; shift;;
-	--)			shift; break;;
-	-*)			{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
-	*)			break;;
+	--)		shift; break;;
+	-*)		if argCount=$(runWithPrompt --understands "$@"); then
+			    while ((argCount-- > 0))
+			    do
+				runWithPromptArgs+=("$1"); shift
+			    done
+			elif [ $? -eq 2 ]; then
+			    exit 2
+			else
+			    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2
+			fi
+			;;
+	*)		break;;
     esac
 done
 if [ $# -ne 0 ]; then
