Reimplementation: Replace redir-p implementation with toFile
These were mostly identical, but the more recent toFile has a better implementation and more features. However, the name redir-p is better.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/redir-p b/bin/redir-p
--- a/bin/redir-p
+++ b/bin/redir-p
@@ -1,10 +1,16 @@
 #!/bin/bash
+set -o pipefail
+
+: ${REDIRP_COMMAND_JOINER=;}
+: ${REDIRP_EXEC_END=;}
 
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: cat FILE [...] | [DEBUG=sudo[!]] %q %s\n' "$(basename "$1")" '[--sudo] [-m|--mode MODE] [-v|--verbose] [-a|--append] [-t|--tee] [--] FILE [-?|-h|--help]'
+    printf 'Usage: [DEBUG=sudo[!]] %q %s\n' "$(basename "$1")" '[--] TARGET-FILE [--sudo] [-m|--mode MODE] [-v|--verbose] [-a|--append] [-t|--tee] [-?|-h|--help] ...'
+    printf 'Usage: %q %s\n' "$(basename "$1")" "... [-1|--stdout|-2|--stderr] -c|--command \"COMMANDLINE\" [-c ...] | --exec SIMPLECOMMAND [...] ${REDIRP_EXEC_END} [--exec ...] | [--] SIMPLECOMMAND [...]"
+    printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '...'
 }
 printUsage()
 {
@@ -18,28 +24,42 @@ printLongUsage()
     # This is the long "man page" when launched with the help argument.
     # It is printed to stdout to allow paging with 'more'.
     cat <<HELPDESCRIPTION
-Redirect standard input into FILE while ensuring that FILE can be created by
-creating parent directories as needed.
+Create a TARGET-FILE from standard input / COMMAND output, automatically
+creating missing parent directories if necessary.
 HELPDESCRIPTION
     echo
     printShortUsage "$1"
     echo
     cat <<HELPTEXT
-    --sudo		Create / write with sudo unless already running as the
-			superuser.
+    --sudo		Create with sudo unless the target directory is
+			writeable by the current user or we're already running
+			as the superuser.
     --mode|-m MODE	Set file mode (as in chmod).
-    --verbose|-v	Print a message for each created directory.
-    --append|-a		Append to FILE instead of overwriting it.
-    --tee|-t		Also print the output in addition to piping it.
-
-SEE ALSO:
-- touch-p just creates FILE without providing / updating contents.
+    --verbose|-v	Print a message for a created directory.
+    --append|-a		Append to TARGET-FILE instead of overwriting it.
+    --tee|-t		Also print the input in addition to putting it into
+			TARGET-FILE. This then works like tee, but with
+			auto-creation of missing parent directories.
+    --stdout|-1		Only put standard output into TARGET-FILE; error output
+			is left alone and output normally.
+    --stderr|-2		Only put error output into TARGET-FILE; other output is
+			left alone and output normally.
+    --command|-c CMD	Execute CMD as a command-line and put its output into
+			TARGET-FILE.
+    --exec CMD [...] ${REDIRP_EXEC_END}	Execute CMD and put its output into TARGET-FILE; all
+			following arguments are taken to be arguments to the CMD
+			until an argument consisting of '${REDIRP_EXEC_END}' is encountered.
 HELPTEXT
 }
-sudoArg=
+
 typeset -a mkdirArgs=()
-isAppend=
+sudoArg=
+sudoTeeRedir='>/dev/null'
+redir='>'
 isTee=
+capturePrefix='2>&1'
+captureSuffix=
+typeset -a teeArg=()
 while [ $# -ne 0 ]
 do
     case "$1" in
@@ -49,36 +69,65 @@ do
 	--verbose|-v)	mkdirArgs+=("$1"); shift;;
 	--mode|-m)	mkdirArgs+=("$1" "$2"); shift; shift;;
 
-	--append|-a)	shift; isAppend=t;;
-	--tee|-t)	shift; isTee=t;;
-	--)		shift; break;;
-	-)		break;; # For supporting special - FILE without prior --
+	--append|-a)	teeArg=("$1"); shift; redir='>>';;
+	--tee|-t)	shift; isTee=t; sudoTeeRedir='';;
+
+	--stdout|-1)	shift; capturePrefix='';;
+	--stderr|-2)	shift; capturePrefix='3>&1 1>&2 2>&3 3>&-'; captureSuffix='3>&1 1>&2 2>&3 3>&-';;
+	--command|-c)	shift; commands+="${commands:+ $REDIRP_COMMAND_JOINER }${1?}"; shift;;
+	--exec)		shift
+			cmd=
+			while [ $# -gt 0 -a "$1" != "$REDIRP_EXEC_END" ]
+			do
+			    printf -v quotedArg %q "$1"
+			    cmd+="${cmd:+ }${quotedArg}"
+			    shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo "ERROR: --exec command must be concluded with '${REDIRP_EXEC_END}'"; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			shift
+			commands+="${commands:+ $REDIRP_COMMAND_JOINER }${cmd}"
+			;;
+	--)		shift
+			[ -z "$targetFilespec" ] || break
+			if [ $# -eq 0 ]; then
+			    echo 'ERROR: No TARGET-FILE passed.'
+			    echo
+			    printUsage "$0"
+			    exit 2
+			fi >&2
+			targetFilespec="${1:?}"; shift
+			;;
 	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
-	*)		break;;
+	*)		[ -z "$targetFilespec" ] || break
+			targetFilespec="${1:?}"; shift
+			;;
     esac
 done
-if [ $# -ne 1 ]; then
-    printUsage "$0" >&2
-    exit 2
+if [ $# -ne 0 ]; then
+    # Combine --command and SIMPLECOMMAND; need to quote SIMPLECOMMAND to
+    # undo the effects of eval.
+    printf -v quotedSimpleCommand '%q ' "$@"
+    commands+="${commands:+ $REDIRP_COMMAND_JOINER }${quotedSimpleCommand% }"
 fi
-filespec="$1"; shift
 
-SUDO="$sudoArg"; [ $EUID -eq 0 ] && SUDO=''
+SUDO="$sudoArg"; [ $EUID -eq 0 ] || [ -w "$targetDirspec" ] && SUDO=''
 [ -n "$sudoArg" ] && case ",${DEBUG:-}," in *,sudo,*) SUDO="verbose $SUDO";; *,sudo\!,*) SUDO="echotrace $SUDO";; esac
 
-dirspec="$(dirname -- "$filespec")"
-[ -d "$dirspec" ] || $SUDO mkdir --parents "${mkdirArgs[@]}" -- "$dirspec" || exit $?
+targetDirspec="$(dirname -- "$targetFilespec")"
+[ -d "$targetDirspec" ] || $SUDO mkdir --parents "${mkdirArgs[@]}" -- "$targetDirspec" || exit $?
 
-if [ -n "$SUDO" ]; then
-    if [ "$isTee" ]; then
-	exec $SUDO tee ${isAppend:+--append} -- "$filespec"
+capture()
+{
+    if [ -n "$SUDO" ]; then
+	eval '$SUDO tee "${teeArg[@]}" -- "$targetFilespec"' "$sudoTeeRedir"
+    elif [ "$isTee" ]; then
+	tee "${teeArg[@]}" -- "$targetFilespec"
     else
-	exec $SUDO tee ${isAppend:+--append} -- "$filespec" >/dev/null
+	eval "cat $redir \"\$targetFilespec\""
     fi
-else
-    if [ "$isTee" ]; then
-	exec tee ${isAppend:+--append} -- "$filespec"
-    else
-	eval "exec cat >${isAppend:+>} \"\$filespec\""
-    fi
-fi
+}
+
+eval "${commands:+{ { }${commands}${commands:+; \} $capturePrefix | }capture${commands:+; \} $captureSuffix}"
