ENH: Consistency: Support --exec in addition to --command

diff --git a/bin/tempedit b/bin/tempedit
--- a/bin/tempedit
+++ b/bin/tempedit
@@ -9,11 +9,11 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: [TMPDIR=DIR] %q %s\n' "$(basename "$1")" "[-d|--directory DIR] [-b|--basename BASE] [-e|--extension EXT] -P|--no-print [-C|--cleanup] [--edit-empty] [-s|--sink-command \"COMMANDLINE\" [-s ...] | -S|--sink-exec SIMPLE-SINK-COMMAND [...] $TEMPEDIT_EXEC_END [...] [-p|--print]] -c|--command \"COMMANDLINE\" [-c ...] [--] SIMPLECOMMAND [...] [-?|-h|--help]"
+    printf 'Usage: [TMPDIR=DIR] %q %s\n' "$(basename "$1")" "[-d|--directory DIR] [-b|--basename BASE] [-e|--extension EXT] -P|--no-print [-C|--cleanup] [--edit-empty] [-s|--sink-command \"COMMANDLINE\" [-s ...] | -S|--sink-exec SIMPLE-SINK-COMMAND [...] $TEMPEDIT_EXEC_END [-S ...] [-p|--print]] -c|--command \"COMMANDLINE\" [-c ...] | --exec SIMPLECOMMAND [...] ${TEMPEDIT_EXEC_END} [--exec ...] [--] SIMPLECOMMAND [...] [-?|-h|--help]"
     echo
-    printf 'Usage: cat FILE [...] | [TMPDIR=DIR] %q %s\n' "$(basename "$1")" "[-d|--directory DIR] [-b|--basename BASE] [-e|--extension EXT] -P|--no-print [-C|--cleanup] [--edit-empty] [-s|--sink-command \"COMMANDLINE\" [-s ...] | -S|--sink-exec SIMPLE-SINK-COMMAND [...] $TEMPEDIT_EXEC_END [...] [-p|--print]]"
+    printf 'Usage: cat FILE [...] | [TMPDIR=DIR] %q %s\n' "$(basename "$1")" "[-d|--directory DIR] [-b|--basename BASE] [-e|--extension EXT] -P|--no-print [-C|--cleanup] [--edit-empty] [-s|--sink-command \"COMMANDLINE\" [-s ...] | -S|--sink-exec SIMPLE-SINK-COMMAND [...] $TEMPEDIT_EXEC_END [-S ...] [-p|--print]]"
     echo
-    printf 'Usage: cat FILE [...] | result=$([TMPDIR=DIR] %q %s)\n' "$(basename "$1")" "[-d|--directory DIR] [-b|--basename BASE] [-e|--extension EXT] [-P|--no-print [-C|--cleanup]] [--edit-empty] [-s|--sink-command \"COMMANDLINE\" [-s ...] | -S|--sink-exec SIMPLE-SINK-COMMAND [...] $TEMPEDIT_EXEC_END [...] [-p|--print]]"
+    printf 'Usage: cat FILE [...] | result=$([TMPDIR=DIR] %q %s)\n' "$(basename "$1")" "[-d|--directory DIR] [-b|--basename BASE] [-e|--extension EXT] [-P|--no-print [-C|--cleanup]] [--edit-empty] [-s|--sink-command \"COMMANDLINE\" [-s ...] | -S|--sink-exec SIMPLE-SINK-COMMAND [...] $TEMPEDIT_EXEC_END [-S ...] [-p|--print]]"
 }
 printUsage()
 {
@@ -59,6 +59,9 @@ HELPDESCRIPTION
 			are joined with | as pipeline steps.
     --command|-c CMD	The command whose output is captured. When this is a
 			simple command, it can also be passed as such.
+    --exec CMD [...] ${TEMPEDIT_EXEC_END}	The command whose output is captured; all following
+			arguments are taken to be arguments to the CMD until an
+			argument consisting of '${TEMPEDIT_EXEC_END}' is encountered.
 HELPTEXT
 }
 
@@ -102,6 +105,22 @@ do
 			isPrint=
 			;;
 	--command|-c)	shift; commands+=(${commands:+;} "$1"); isNeedEval=t; shift;;
+	--exec)		shift
+			cmd=
+			while [ $# -gt 0 -a "$1" != "$TEMPEDIT_EXEC_END" ]
+			do
+			    printf -v quotedArg '%q' "$1"
+			    cmd="${cmd}${cmd:+ }${quotedArg}"
+			    shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo "ERROR: --exec command must be concluded with '${TEMPEDIT_EXEC_END}'"; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			shift
+			commands+=(${commands:+;} "$cmd")
+			isNeedEval=t
+			;;
 	--)		shift; break;;
 	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
diff --git a/bin/withAliasedCommand b/bin/withAliasedCommand
--- a/bin/withAliasedCommand
+++ b/bin/withAliasedCommand
@@ -3,12 +3,13 @@ set -o pipefail
 shopt -qs extglob
 
 : ${WITHALIASEDCOMMAND_ALIAS_END=;}
+: ${WITHALIASEDCOMMAND_EXEC_END=;}
 
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" "NAME=ALIAS-COMMAND|-n|--name NAME --as ALIAS-COMMAND|-n|--name NAME --alias ALIAS-COMMAND [...] ${WITHALIASEDCOMMAND_ALIAS_END}|-n|--name NAME --alias-command ALIAS-COMMANDLINE [...] -c|--command \"COMMANDLINE\" [-c ...] | [--] SIMPLECOMMAND [...] [-?|-h|--help]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "NAME=ALIAS-COMMAND|-n|--name NAME --as ALIAS-COMMAND|-n|--name NAME --alias ALIAS-COMMAND [...] ${WITHALIASEDCOMMAND_ALIAS_END}|-n|--name NAME --alias-command ALIAS-COMMANDLINE [...] -c|--command \"COMMANDLINE\" [-c ...] | --exec SIMPLECOMMAND [...] ${WITHALIASEDCOMMAND_EXEC_END} [--exec ...] | [--] SIMPLECOMMAND [...] [-?|-h|--help]"
     echo
     printf 'Usage: echo COMMANDLINES | %q %s\n' "$(basename "$1")" '[...] [--bare|[--trailing-prompt|--no-trailing-prompt] [--emulate-prompt] [--worst-status]]'
     echo
@@ -50,6 +51,9 @@ HELPDESCRIPTION
 			ALIAS-COMMAND.
     --command|-c CMD	The command line to be executed. When this is a simple
 			command, it can also be passed as such.
+    --exec CMD [...] ${WITHALIASEDCOMMAND_EXEC_END}	Execute CMD; all following arguments are taken to be
+			arguments to the CMD until an argument consisting of
+			'${WITHALIASEDCOMMAND_EXEC_END}' is encountered.
     --bare		Do not print a status line before and after launching
 			the COMMAND.
     --trailing-prompt	Customizations of the prompt emulation around COMMAND;
@@ -161,6 +165,23 @@ do
 			;;
 
 	--command|-c)	shift; commands+=(${commands:+;} "$1"); isNeedEval=t; shift;;
+	--exec)		shift
+			cmd=
+			while [ $# -gt 0 -a "$1" != "$WITHALIASEDCOMMAND_EXEC_END" ]
+			do
+			    printf -v quotedArg '%q' "$1"
+			    cmd="${cmd}${cmd:+ }${quotedArg}"
+			    shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo "ERROR: --exec command must be concluded with '${WITHALIASEDCOMMAND_EXEC_END}'"; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			shift
+			commands+=(${commands:+;} "$cmd")
+			isNeedEval=t
+			;;
+
 	--bare)		shift; isBare=t;;
 	--no-trailing-prompt|--trailing-prompt|--emulate-prompt|--worst-status)  runWithPromptArgs+=("$1"); shift;;
 	--)		shift; break;;
diff --git a/bin/withDeltaCommand b/bin/withDeltaCommand
--- a/bin/withDeltaCommand
+++ b/bin/withDeltaCommand
@@ -8,7 +8,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" "-d|--delta-command DELTA-COMMANDLINE | -D|--delta-exec SIMPLE-DELTA-COMMAND [...] $WITHDELTACOMMAND_EXEC_END [...] -c|--command \"COMMANDLINE\" [-c ...] | [--] SIMPLECOMMAND [...] [-?|-h|--help]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "-d|--delta-command DELTA-COMMANDLINE | -D|--delta-exec SIMPLE-DELTA-COMMAND [...] $WITHDELTACOMMAND_EXEC_END [...] -c|--command \"COMMANDLINE\" [-c ...] | --exec SIMPLECOMMAND [...] ${WITHDELTACOMMAND_EXEC_END} [--exec ...] | [--] SIMPLECOMMAND [...] [-?|-h|--help]"
     echo
     printf 'Usage: echo COMMANDLINES | %q %s\n' "$(basename "$1")" '[...] [--bare|[--trailing-prompt|--no-trailing-prompt] [--emulate-prompt] [--worst-status]]'
     echo
@@ -41,6 +41,9 @@ HELPDESCRIPTION
 			encountered.
     --command|-c CMD	The command line to be executed. When this is a simple
 			command, it can also be passed as such.
+    --exec CMD [...] ${WITHDELTACOMMAND_EXEC_END}	Execute CMD; all following arguments are taken to be
+			arguments to the CMD until an argument consisting of
+			'${WITHDELTACOMMAND_EXEC_END}' is encountered.
     --bare		Do not print a status line before and after launching
 			the COMMAND.
     --trailing-prompt	Customizations of the prompt emulation around COMMAND;
@@ -84,6 +87,22 @@ do
 			deltaCommands+=(${deltaCommands:+;} "$cmd")
 			;;
 	--command|-c)	shift; commands+=(${commands:+;} "$1"); isNeedEval=t; shift;;
+	--exec)		shift
+			cmd=
+			while [ $# -gt 0 -a "$1" != "$WITHDELTACOMMAND_EXEC_END" ]
+			do
+			    printf -v quotedArg '%q' "$1"
+			    cmd="${cmd}${cmd:+ }${quotedArg}"
+			    shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo "ERROR: --exec command must be concluded with '${WITHDELTACOMMAND_EXEC_END}'"; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			shift
+			commands+=(${commands:+;} "$cmd")
+			isNeedEval=t
+			;;
 	--bare)		shift; isBare=t;;
 	--no-trailing-prompt|--trailing-prompt|--emulate-prompt|--worst-status)  runWithPromptArgs+=("$1"); shift;;
 	--)		shift; break;;
diff --git a/bin/withOutputToSinkBasedOnStatus b/bin/withOutputToSinkBasedOnStatus
--- a/bin/withOutputToSinkBasedOnStatus
+++ b/bin/withOutputToSinkBasedOnStatus
@@ -8,7 +8,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" "--success-command SINK-COMMANDLINE | --success-exec SIMPLE-SINK-COMMAND [...] $WITHOUTPUTTOSINKBASEDONSTATUS_EXEC_END | --fail-command SINK-COMMANDLINE | --fail-exec SIMPLE-SINK-COMMAND [...] $WITHOUTPUTTOSINKBASEDONSTATUS_EXEC_END | -s|--status-command STATUS|-S|[!]S|S+|S-T|S%T SINK-COMMANDLINE | -S|--status-exec STATUS|-S|[!]S|S+|S-T|S%T SIMPLE-SINK-COMMAND [...] $WITHOUTPUTTOSINKBASEDONSTATUS_EXEC_END [...] [-t|--tee] [-1|--stdout|-2|--stderr] -c|--command \"COMMANDLINE\" [-c ...] | [--] SIMPLECOMMAND [...] [-?|-h|--help]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "--success-command SINK-COMMANDLINE | --success-exec SIMPLE-SINK-COMMAND [...] $WITHOUTPUTTOSINKBASEDONSTATUS_EXEC_END | --fail-command SINK-COMMANDLINE | --fail-exec SIMPLE-SINK-COMMAND [...] $WITHOUTPUTTOSINKBASEDONSTATUS_EXEC_END | -s|--status-command STATUS|-S|[!]S|S+|S-T|S%T SINK-COMMANDLINE | -S|--status-exec STATUS|-S|[!]S|S+|S-T|S%T SIMPLE-SINK-COMMAND [...] $WITHOUTPUTTOSINKBASEDONSTATUS_EXEC_END [...] [-t|--tee] [-1|--stdout|-2|--stderr] -c|--command \"COMMANDLINE\" [-c ...] | --exec SIMPLECOMMAND [...] ${WITHOUTPUTTOSINKBASEDONSTATUS_EXEC_END} [--exec ...] | [--] SIMPLECOMMAND [...] [-?|-h|--help]"
     echo
     printf 'Usage: echo COMMANDLINES | %q %s\n' "$(basename "$1")" '[...] [--bare|[--trailing-prompt|--no-trailing-prompt] [--emulate-prompt] [--worst-status]]'
     echo
@@ -74,6 +74,9 @@ HELPDESCRIPTION
     --stderr|-2		Only pipe error output; other output is output normally.
     --command|-c CMD	The command line to be captured. When this is a simple
 			command, it can also be passed as such.
+    --exec CMD [...] ${WITHOUTPUTTOSINKBASEDONSTATUS_EXEC_END}	Execute CMD; all following arguments are taken to be
+			arguments to the CMD until an argument consisting of
+			'${WITHOUTPUTTOSINKBASEDONSTATUS_EXEC_END}' is encountered.
     --bare		Do not print a status line before and after launching
 			the COMMAND.
     --trailing-prompt	Customizations of the prompt emulation around COMMAND;
@@ -173,6 +176,22 @@ do
 			statusSinkCommands["$status"]+="${statusSinkCommands["$status"]:+|}$cmd"
 			;;
 	--command|-c)	shift; commands+=(${commands:+;} "$1"); isNeedEval=t; shift;;
+	--exec)		shift
+			cmd=
+			while [ $# -gt 0 -a "$1" != "$WITHOUTPUTTOSINKBASEDONSTATUS_EXEC_END" ]
+			do
+			    printf -v quotedArg '%q' "$1"
+			    cmd="${cmd}${cmd:+ }${quotedArg}"
+			    shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo "ERROR: --exec command must be concluded with '${WITHOUTPUTTOSINKBASEDONSTATUS_EXEC_END}'"; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			shift
+			commands+=(${commands:+;} "$cmd")
+			isNeedEval=t
+			;;
 	--bare)		shift; isBare=t;;
 	--no-trailing-prompt|--trailing-prompt|--emulate-prompt|--worst-status)  runWithPromptArgs+=("$1"); shift;;
 	--)		shift; break;;
