ENH: Allow generation without passed FILE(s) via --generation-{command,exec}
The supplied command may also / only be able to provide the filespecs without any inputs. If the inputs are hard-coded, it's easier to inline those directly in the SELECT-COMMAND than passing them separately as FILE(s) (even if --files makes that easier for wrappers).
It's a bit unfortunate that for pure generator use the withSelectedFiles name is misleading, but both code reuse and the possibility to combine generator and select-command make it unattractive to implement a separate withGeneratedFiles command instead.

diff --git a/bin/withSelectedFiles b/bin/withSelectedFiles
--- a/bin/withSelectedFiles
+++ b/bin/withSelectedFiles
@@ -11,12 +11,12 @@ selectFileMarker="$WITHSELECTEDFILES_SELECTED_FILE_MARKER"; unset WITHSELECTEDFI
 
 printShortUsage()
 {
-    local commonArgs="--select-command \"SELECT-COMMANDLINE\" [--select-command ...] | --select-exec SELECT-SIMPLECOMMAND [...] ${WITHSELECTEDFILES_SELECTED_EXEC_END} [--select-exec ...] -c|--command \"COMMANDLINE\" [-c ...] | --exec SIMPLECOMMAND [...] ${WITHSELECTEDFILES_EXEC_END} [--exec ...] | SIMPLECOMMAND [...]"
+    local commonArgs="--generator-command \"GENERATOR-COMMANDLINE\" [--generator-command ...] | --generator-exec GENERATOR-SIMPLECOMMAND [...] ${WITHSELECTEDFILES_SELECTED_EXEC_END} [--generator-exec ...] | --select-command \"SELECT-COMMANDLINE\" [--select-command ...] | --select-exec SELECT-SIMPLECOMMAND [...] ${WITHSELECTEDFILES_SELECTED_EXEC_END} [--select-exec ...] -c|--command \"COMMANDLINE\" [-c ...] | --exec SIMPLECOMMAND [...] ${WITHSELECTEDFILES_EXEC_END} [--exec ...] | SIMPLECOMMAND [...]"
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
     printf 'Usage: %q %s\n' "$(basename "$1")" "${commonArgs} [--] FILE [...] [-?|-h|--help]"
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" "-f|--files FILE [...] ${WITHSELECTEDFILES_FILES_END} [-f ...] ${commonArgs} [-?|-h|--help]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "-f|--files [FILE ...] ${WITHSELECTEDFILES_FILES_END} [-f ...] ${commonArgs} [-?|-h|--help]"
 }
 printUsage()
 {
@@ -31,8 +31,9 @@ printLongUsage()
     # It is printed to stdout to allow paging with 'more'.
     cat <<HELPDESCRIPTION
 Execute COMMAND on the file(s) (which ${fileMarker:+either }are appended${fileMarker:+ or replace any
-$fileMarker marker} inside COMMANDLINE) that are selected by SELECT-COMMAND. Any passed
-FILE(s) ${selectFileMarker:+either }are appended${selectFileMarker:+ or replace any $selectFileMarker marker} inside SELECT-COMMAND.
+$fileMarker marker} inside COMMANDLINE) that are generated by GENERATOR-COMMAND or
+selected by SELECT-COMMAND. Any passed FILE(s) ${selectFileMarker:+either }are appended${selectFileMarker:+ or replace
+any $selectFileMarker marker} inside SELECT-COMMAND.
 HELPDESCRIPTION
     echo
     printShortUsage "$1"
@@ -44,6 +45,13 @@ HELPDESCRIPTION
     --files|-f FILE [...] ${WITHSELECTEDFILES_FILES_END}
 			Take FILE(s) separately, don't parse FILE(s) at the end;
 			all arguments there belong to SIMPLECOMMAND.
+
+FILE(s) are mandatory if only SELECT-COMMAND is provided; if only
+GENERATOR-COMMAND is provided, all trailing arguments (even those after --) are
+simply added to SIMPLECOMMAND, and the --files parameter is forbidden.
+If both are provided, FILE(s) are parsed; if none are given then
+GENERATOR-COMMAND is executed.
+
 SEE ALSO:
 - withFirstExistingFile only passes the first existing file to COMMAND.
 - eachFile executes COMMAND on each FILE individually, not just on the first.
@@ -51,11 +59,13 @@ SEE ALSO:
 EXIT STATUS:
     2	Bad invocation, wrong or missing command-line arguments.
     3	Internal error or failed assertion.
-    4	No files have been selected by SELECT-COMMAND.
+    4	No files have been generated by GENERATOR-COMMAND / selected by
+	SELECT-COMMAND.
     *   any exit status from COMMAND(s)
 HELPTEXT
 }
 
+generatorCommands=
 selectCommands=
 typeset -a filespecs=()
 commands=
@@ -74,7 +84,7 @@ do
 			    exit 2
 			fi >&2
 			shift
-			if [ ${#filespecs[@]} -eq 0 ]; then
+			if [ -z "$generatorCommands" -a ${#filespecs[@]} -eq 0 ]; then
 			    echo 'ERROR: --files|-f must be followed by at least one FILE.'; echo; printUsage "$0"
 			    exit 2
 			fi >&2
@@ -99,6 +109,25 @@ do
 	--select-command)
 			shift; selectCommands+="${selectCommands:+ ; }$1"; shift;;
 
+	--generator-exec)
+			shift
+			cmd=
+			while [ $# -gt 0 -a "$1" != "$WITHSELECTEDFILES_SELECTED_EXEC_END" ]
+			do
+			    printf -v quotedArg '%q' "$1"
+			    cmd="${cmd}${cmd:+ }${quotedArg}"
+			    shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo "ERROR: --generator-exec command must be concluded with '${WITHSELECTEDFILES_SELECTED_EXEC_END}'"; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			shift
+			generatorCommands+="${generatorCommands:+ ; }${cmd}"
+			;;
+	--generator-command)
+			shift; commands+="${generatorCommands:+ ; }$1"; shift;;
+
 	--exec)		shift
 			cmd=
 			printf -v escapedFileMarker %q "$fileMarker"
@@ -119,7 +148,7 @@ do
 	--)		shift; break;;
 	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		typeset -a files=()
-			if [ ${#filespecs[@]} -eq 0 ] && ! contains -- "$@"; then
+			if [ ${#filespecs[@]} -eq 0 -a -n "$selectCommands" ] && ! contains -- "$@"; then
 			    while [ $# -gt 0 ]
 			    do
 				lastArg="${!#}"
@@ -131,7 +160,7 @@ do
 
 			if [ $# -gt 0 ]; then
 			    typeset -a cmd=()
-			    while [ $# -gt 0 ] && [ ${#filespecs[@]} -gt 0 -o "$1" != -- ]  # Note: No stopping at -- if --files is used.
+			    while [ $# -gt 0 ] && [ ${#filespecs[@]} -gt 0 -o -z "$selectCommands" -o "$1" != -- ]  # Note: No stopping at -- if no SELECT-COMMAND or --files is used.
 			    do
 				cmd+=("$1")
 				shift
@@ -151,8 +180,8 @@ do
     esac
 done
 filespecs+=("$@")
-if [ -z "$selectCommands" ]; then
-    echo "ERROR: No SELECT-COMMAND(s) specified; need to pass --select-command \"SELECT-COMMANDLINE\", or --select-exec SELECT-SIMPLECOMMAND [...] ${WITHSELECTEDFILES_SELECTED_EXEC_END}"
+if [ -z "$generatorCommands" -a -z "$selectCommands" ]; then
+    echo "ERROR: No GENERATOR-COMMAND(s) nor SELECT-COMMAND(s) specified; need to pass --generator-command \"GENERATOR-COMMANDLINE\", or --generator-exec GENERATOR-SIMPLECOMMAND [...] ${WITHSELECTEDFILES_SELECTED_EXEC_END} and/or --select-command \"SELECT-COMMANDLINE\", or --select-exec SELECT-SIMPLECOMMAND [...] ${WITHSELECTEDFILES_SELECTED_EXEC_END}"
     echo
     printUsage "$0"
     exit 2
@@ -161,18 +190,28 @@ elif [ -z "$commands" ]; then
     echo
     printUsage "$0"
     exit 2
-elif [ ${#filespecs[@]} -eq 0 ]; then
+elif [ -z "$generatorCommands" -a ${#filespecs[@]} -eq 0 ]; then
     echo 'ERROR: No FILE(s) passed.'
+    echo
+    printUsage "$0"
+    exit 2
+elif [ -z "$selectCommands" -a ${#filespecs[@]} -gt 0 ]; then
+    echo 'ERROR: Passed FILE(s) are ignored by the GENERATOR-COMMAND, as no SELECT-COMMAND is provided.'
     echo
     printUsage "$0"
     exit 2
 fi >&2
 
-printf -v quotedFiles '%q ' "${filespecs[@]}"; quotedFiles="${quotedFiles% }"
-typeset -a s=("${filespecs[@]}")
-interpolatedSelectCommands="${selectCommands//"$selectFileMarker"/$quotedFiles}"
-[ "$interpolatedSelectCommands" = "$selectCommands" ] || s=()
-readarray -t selectedFiles < <(eval "$interpolatedSelectCommands" '"${s[@]}"')
+typeset -a s=()
+if [ ${#filespecs[@]} -gt 0 ]; then
+    printf -v quotedFiles '%q ' "${filespecs[@]}"; quotedFiles="${quotedFiles% }"
+    s=("${filespecs[@]}")
+    sourceCommands="${selectCommands//"$selectFileMarker"/$quotedFiles}"
+    [ "$sourceCommands" = "$selectCommands" ] || s=()
+else
+    sourceCommands="$generatorCommands"
+fi
+readarray -t selectedFiles < <(eval "$sourceCommands" '"${s[@]}"')
 if [ ${#selectedFiles[@]} -eq 0 ]; then
     exit 4
 fi
