withTemp{Dir,File}: ENH: Minor: Also support --exec in addition to --command
System-info: Ubuntu 24.04.3 LTS, x86_64
Platform-info: bash 5.2.21(1)-release, Bats 1.10.0

diff --git a/bin/withTempfile b/bin/withTempfile
--- a/bin/withTempfile
+++ b/bin/withTempfile
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 : ${WITHTEMPFILE_COMMAND_JOINER=;}
+: ${WITHTEMPFILE_EXEC_END=;}
 : ${WITHTEMPFILE_FILE_MARKER='{}'}
 fileMarker="$WITHTEMPFILE_FILE_MARKER"; unset WITHTEMPFILE_FILE_MARKER
 
@@ -8,7 +9,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-p|--tmpdir DIRSPEC] [-n|--name NAME] [--move|-m|--move-on-success|-M|--move-on-failure|--rename|-r|--rename-on-success|-R|--rename-on-failure] [--keep|-k|--keep-on-success|-K|--keep-on-failure] -c|--command "COMMANDLINE" [-c ...] | [--] SIMPLECOMMAND [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" "[-p|--tmpdir DIRSPEC] [-n|--name NAME] [--move|-m|--move-on-success|-M|--move-on-failure|--rename|-r|--rename-on-success|-R|--rename-on-failure] [--keep|-k|--keep-on-success|-K|--keep-on-failure] -c|--command \"COMMANDLINE\" [-c ...] | --exec SIMPLECOMMAND [...]${fileMarker:+ [}${fileMarker}${fileMarker:+] [...]} ${WITHTEMPFILE_EXEC_END} [--exec ...] | [--] SIMPLECOMMAND [...]${fileMarker:+ [}${fileMarker}${fileMarker:+] [...]} [-?|-h|--help]"
     echo
     printf 'Usage: echo COMMANDLINES | %q %s\n' "$(basename "$1")" "[...] [--bare|$(runWithPrompt --get-short-usage 2>/dev/null)]"
     echo
@@ -58,6 +59,10 @@ HELPDESCRIPTION
 			Do not clean up the tempfile if COMMAND(s) fail.
     --command|-c CMD	The command line to be executed. When this is a simple
 			command, it can also be passed as such.
+    --exec CMD [...] ${WITHTEMPFILE_EXEC_END}	Execute CMD; all following arguments are taken to be
+			arguments to the CMD until an argument consisting of
+			'${WITHTEMPFILE_EXEC_END}' is encountered.${fileMarker:+ The string $fileMarker is replaced by the
+			tempfile.}
     --bare		Do not print a status line before and after launching
 			the COMMAND.
 HELPTEXT
@@ -122,6 +127,22 @@ do
 	--keep-on-failure|-K)
 			shift; keepOp=-ne;;
 	--command|-c)	shift; commands+="${commands:+ $WITHTEMPFILE_COMMAND_JOINER }$1"; shift;;
+	--exec)		shift
+			cmd=
+			printf -v escapedFileMarker %q "$fileMarker"
+			while [ $# -gt 0 -a "$1" != "$WITHTEMPFILE_EXEC_END" ]
+			do
+			    printf -v quotedArg %q "$1"
+			    cmd+="${cmd:+ }${quotedArg//"$escapedFileMarker"/$fileMarker}"	# %q escapes {}, we don't want that to have it interpolated later.
+			    shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo "ERROR: --exec command must be concluded with '${WITHTEMPFILE_EXEC_END}'"; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			shift
+			commands+="${commands:+ $WITHTEMPFILE_COMMAND_JOINER }${cmd}"
+			;;
 	--bare)		shift; isBare=t; runWithCommand=runWith;;
 	--exit-on-failure)
 			bashArgs+=(-e); runWithPromptArgs+=("$1"); shift;;
