{slowcommand,with{Home,Path}}: Removed: Drop the reading of COMMANDLINES from stdin / runWithPrompt
All of these tools do just a single invocation of supplied COMMAND(s) with a changed environment. We don't need to include the runWithPrompt functionality in there; if really needed, the corresponding functionality can be composed:
    $ echo -e 'uname -a\nsleep 1\nhostname' | slowcommand 10 bash -e -
    $ echo -e 'uname -a\nsleep 1\nhostname' | slowcommand 10 runWithPrompt
(There are other tools that do multiple invocations of the passed COMMAND(s); these really need to integrate runWithPrompt to give the appearance of interactive shell invocation; it cannot be composed there.)

diff --git a/bin/withHome b/bin/withHome
--- a/bin/withHome
+++ b/bin/withHome
@@ -5,10 +5,6 @@ printShortUsage()
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
     printf 'Usage: %q %s\n' "$(basename "$1")" 'HOME -c|--command "COMMANDLINE" [-c ...] | [--] SIMPLECOMMAND [...] [-?|-h|--help]'
-    echo
-    printf 'Usage: echo COMMANDLINES | %q %s\n' "$(basename "$1")" 'HOME [--bare|[--initial-status NUM] [--trailing-prompt|--no-trailing-prompt] [--no-output-no-prompt] [--no-output-no-error] [--emulate-prompt]] [--no-success-no-count|--no-count-on N] [--exit-on-success|--exit-on-failure|--exit-on NUM] [--worst-status] [--comment COMMENT] [--summarize-failed ERROR-TEXT [--summarize-failed-separator SEP]]'
-    echo
-    printf 'Usage: %q %s <<EOF\n  COMMANDLINE\n...\nEOF\n' "$(basename "$1")" 'HOME [...]'
 }
 printUsage()
 {
@@ -26,26 +22,9 @@ Execute COMMAND while HOME is used as the home directory (\$HOME).
 HELPDESCRIPTION
     echo
     printShortUsage "$1"
+    echo
     cat <<HELPTEXT
 This can be used to temporarily change the home directory.
-
-    --bare		    Do not print a status line before and after
-			    launching the COMMAND.
-    --emulate-prompt	    Customizations of the prompt emulation around
-    --initial-status NUM    COMMAND; cp. runWithPrompt
-    --trailing-prompt
-    --no-trailing-prompt
-    --no-output-no-prompt
-    --no-output-no-error
-    --no-success-no-count   Stop on condition / summarize at end; cp. runWith
-    --no-count-on N
-    --exit-on-success
-    --exit-on-failure	    (This also works with --bare.)
-    --exit-on NUM
-    --worst-status
-    --comment COMMENT
-    --summarize-failed ERROR-TEXT
-    --summarize-failed-separator SEP
 HELPTEXT
 }
 
@@ -62,24 +41,13 @@ fi >&2
 absoluteHome="$(realpath --no-symlinks -- "${1?}")" || exit $?
 export HOME="$absoluteHome"; shift
 
-isBare=
 isNeedEval=
 typeset -a commands=()
-typeset -a bashArgs=()
-runWithCommand=runWithPrompt
-typeset -a runWithPromptArgs=()
 while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
 	--command|-c)	shift; commands+=(${commands:+;} "$1"); isNeedEval=t; shift;;
-	--bare)		shift; isBare=t; runWithCommand=runWith;;
-	--exit-on-failure)
-			bashArgs+=(-e); runWithPromptArgs+=("$1"); shift;;
-	--trailing-prompt|--no-trailing-prompt|--no-output-no-prompt|--no-output-no-error|--no-success-no-count|--exit-on-success|--emulate-prompt|--worst-status)
-			runWithPromptArgs+=("$1"); shift;;
-	--initial-status|--no-count-on|--exit-on|--comment|--summarize-failed|--summarize-failed-separator)
-			runWithPromptArgs+=("$1" "$2"); shift; shift;;
 	--)		shift; break;;
 	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
@@ -96,12 +64,13 @@ if [ $# -ne 0 ]; then
     fi
 fi
 if [ ${#commands[@]} -eq 0 ]; then
-    if [ "$isBare" ] && [ ${#runWithPromptArgs[@]} -eq 0 -o "${#runWithPromptArgs[*]}" = --exit-on-failure ]; then
-	exec bash "${bashArgs[@]}" -
-    else
-	exec ${runWithCommand:?} "${runWithPromptArgs[@]}"
-    fi
-elif [ "$isNeedEval" ]; then
+    echo 'ERROR: No COMMAND(s) specified; need to pass -c|--command "COMMANDLINE", or SIMPLECOMMAND.'
+    echo
+    printUsage "$0"
+    exit 2
+fi >&2
+
+if [ "$isNeedEval" ]; then
     eval "${commands[@]}"
 else
     "${commands[@]}"
