withOutputToSinkBasedOn{Match,Status}: ENH: Add --default-{command,exec} as a fallback if none of the other conditions apply
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/withOutputToSinkBasedOnMatch b/bin/withOutputToSinkBasedOnMatch
--- a/bin/withOutputToSinkBasedOnMatch
+++ b/bin/withOutputToSinkBasedOnMatch
@@ -10,7 +10,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" "-m|--match-command PATTERN SINK-COMMANDLINE | -M|--match-exec PATTERN SIMPLE-SINK-COMMAND [...] $WITHOUTPUTTOSINKBASEDONMATCH_EXEC_END -v|--no-match-command PATTERN SINK-COMMANDLINE | -V|--no-match-exec PATTERN SIMPLE-SINK-COMMAND [...] $WITHOUTPUTTOSINKBASEDONMATCH_EXEC_END [...] [-t|--tee] [-1|--stdout|-2|--stderr] -c|--command \"COMMANDLINE\" [-c ...] | --exec SIMPLECOMMAND [...] ${WITHOUTPUTTOSINKBASEDONMATCH_EXEC_END} [--exec ...] | [--] SIMPLECOMMAND [...] [-?|-h|--help]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "-m|--match-command PATTERN SINK-COMMANDLINE | -M|--match-exec PATTERN SIMPLE-SINK-COMMAND [...] $WITHOUTPUTTOSINKBASEDONMATCH_EXEC_END -v|--no-match-command PATTERN SINK-COMMANDLINE | -V|--no-match-exec PATTERN SIMPLE-SINK-COMMAND [...] $WITHOUTPUTTOSINKBASEDONMATCH_EXEC_END [...] | -d|--default-command SINK-COMMANDLINE | -D|--default-exec SIMPLE-SINK-COMMAND [...] $WITHOUTPUTTOSINKBASEDONMATCH_EXEC_END [-t|--tee] [-1|--stdout|-2|--stderr] -c|--command \"COMMANDLINE\" [-c ...] | --exec SIMPLECOMMAND [...] ${WITHOUTPUTTOSINKBASEDONMATCH_EXEC_END} [--exec ...] | [--] SIMPLECOMMAND [...] [-?|-h|--help]"
     echo
     printf 'Usage: echo COMMANDLINES | %q %s\n' "$(basename "$1")" "[...] [--bare|$(runWithPrompt --get-short-usage 2>/dev/null)]"
     echo
@@ -62,6 +62,18 @@ HELPDESCRIPTION
 			steps.
 			PATTERN is a grep-style unanchored basic regular
 			expression.
+    --default-command|-d SINK-COMMANDLINE
+			Execute SINK-COMMAND with the output piped into it if
+			no other SINK-COMMAND [did not] match the output.
+			Multiple SINK-COMMANDs are joined with | as pipeline
+			steps.
+    --default-exec|-D SIMPLE-SINK-COMMAND [...] $WITHOUTPUTTOSINKBASEDONMATCH_EXEC_END
+			Execute SINK-COMMAND with the output piped into it if no
+			other SINK-COMMAND [did not] match the output; all
+			following arguments are taken to be arguments to the
+			SINK-COMMAND until an argument consisting of '${WITHOUTPUTTOSINKBASEDONMATCH_EXEC_END}' is
+			encountered. Multiple SINK-COMMANDs are joined with | as
+			pipeline steps.
     --tee|-t		Also print the output in addition to piping it.
     --stdout|-1		Only pipe output to standard output; error output is
 			output normally.
@@ -96,6 +108,7 @@ teeSuffix=
 isBare=
 typeset -A matchSinkCommands=()
 typeset -A nonMatchSinkCommands=()
+defaultSinkCommands=
 commands=
 typeset -a bashArgs=()
 runWithCommand=runWithPrompt
@@ -115,6 +128,9 @@ do
 			shift
 			pattern="$1"; shift
 			nonMatchSinkCommands["$pattern"]+="${nonMatchSinkCommands["$pattern"]:+ $WITHOUTPUTTOSINKBASEDONMATCH_SINKCOMMAND_JOINER }$1"; shift;;
+	--default-command|-d)
+			shift
+			defaultSinkCommands+="${defaultSinkCommands:+ $WITHOUTPUTTOSINKBASEDONMATCH_SINKCOMMAND_JOINER }$1"; shift;;
 	--match-exec|-M)
 			shift
 			pattern="$1"; shift
@@ -148,6 +164,22 @@ do
 			fi >&2
 			shift
 			nonMatchSinkCommands["$pattern"]+="${nonMatchSinkCommands["$pattern"]:+ $WITHOUTPUTTOSINKBASEDONMATCH_SINKCOMMAND_JOINER }$cmd"
+			;;
+	--default-exec|-D)
+			shift
+			cmd=
+			while [ $# -gt 0 -a "$1" != "$WITHOUTPUTTOSINKBASEDONMATCH_EXEC_END" ]
+			do
+			    printf -v quotedArg '%q' "$1"
+			    cmd="${cmd}${cmd:+ }${quotedArg}"
+			    shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo "ERROR: -D|--default-exec command must be concluded with '${WITHOUTPUTTOSINKBASEDONMATCH_EXEC_END}'"; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			shift
+			defaultSinkCommands+="${defaultSinkCommands:+ $WITHOUTPUTTOSINKBASEDONMATCH_SINKCOMMAND_JOINER }$cmd"
 			;;
 	--command|-c)	shift; commands+="${commands:+ $WITHOUTPUTTOSINKBASEDONMATCH_COMMAND_JOINER }$1"; shift;;
 	--exec)		shift
@@ -224,14 +256,22 @@ typeset -a states=("${PIPESTATUS[@]}")
 [ ${states[1]:-0} -eq 0 ] || exit 3 # Bail on tee failure.
 status=${states[0]}
 
+hasMatch=
 for pattern in "${!matchSinkCommands[@]}"
 do
-    grep --quiet -e "$pattern" -- "$TMPFILE" \
-	&& sinkExecute "${matchSinkCommands["$pattern"]}"
+    if grep --quiet -e "$pattern" -- "$TMPFILE"; then
+	hasMatch=t
+	sinkExecute "${matchSinkCommands["$pattern"]}"
+    fi
 done
 for pattern in "${!nonMatchSinkCommands[@]}"
 do
-    grep --quiet -e "$pattern" -- "$TMPFILE" \
-	|| sinkExecute "${nonMatchSinkCommands["$pattern"]}"
+    if ! grep --quiet -e "$pattern" -- "$TMPFILE"; then
+	hasMatch=t
+	sinkExecute "${nonMatchSinkCommands["$pattern"]}"
+    fi
 done
+if [ ! "$hasMatch" ] && [ -n "$defaultSinkCommands" ]; then
+    sinkExecute "$defaultSinkCommands"
+fi
 exit $status
diff --git a/bin/withOutputToSinkBasedOnStatus b/bin/withOutputToSinkBasedOnStatus
--- a/bin/withOutputToSinkBasedOnStatus
+++ b/bin/withOutputToSinkBasedOnStatus
@@ -10,7 +10,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" "--success-command SINK-COMMANDLINE | --success-exec SIMPLE-SINK-COMMAND [...] $WITHOUTPUTTOSINKBASEDONSTATUS_EXEC_END | --fail-command SINK-COMMANDLINE | --fail-exec SIMPLE-SINK-COMMAND [...] $WITHOUTPUTTOSINKBASEDONSTATUS_EXEC_END | -s|--status-command STATUS|-S|[!]S|S+|S-T|S%T SINK-COMMANDLINE | -S|--status-exec STATUS|-S|[!]S|S+|S-T|S%T SIMPLE-SINK-COMMAND [...] $WITHOUTPUTTOSINKBASEDONSTATUS_EXEC_END [...] [-t|--tee] [-1|--stdout|-2|--stderr] -c|--command \"COMMANDLINE\" [-c ...] | --exec SIMPLECOMMAND [...] ${WITHOUTPUTTOSINKBASEDONSTATUS_EXEC_END} [--exec ...] | [--] SIMPLECOMMAND [...] [-?|-h|--help]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "--success-command SINK-COMMANDLINE | --success-exec SIMPLE-SINK-COMMAND [...] $WITHOUTPUTTOSINKBASEDONSTATUS_EXEC_END | --fail-command SINK-COMMANDLINE | --fail-exec SIMPLE-SINK-COMMAND [...] $WITHOUTPUTTOSINKBASEDONSTATUS_EXEC_END | -s|--status-command STATUS|-S|[!]S|S+|S-T|S%T SINK-COMMANDLINE | -S|--status-exec STATUS|-S|[!]S|S+|S-T|S%T SIMPLE-SINK-COMMAND [...] $WITHOUTPUTTOSINKBASEDONSTATUS_EXEC_END [...] | --default-command SINK-COMMANDLINE | --default-exec SIMPLE-SINK-COMMAND [...] $WITHOUTPUTTOSINKBASEDONSTATUS_EXEC_END [-t|--tee] [-1|--stdout|-2|--stderr] -c|--command \"COMMANDLINE\" [-c ...] | --exec SIMPLECOMMAND [...] ${WITHOUTPUTTOSINKBASEDONSTATUS_EXEC_END} [--exec ...] | [--] SIMPLECOMMAND [...] [-?|-h|--help]"
     echo
     printf 'Usage: echo COMMANDLINES | %q %s\n' "$(basename "$1")" "[...] [--bare|$(runWithPrompt --get-short-usage 2>/dev/null)]"
     echo
@@ -70,6 +70,19 @@ HELPDESCRIPTION
 			taken to be arguments to the SINK-COMMAND until an
 			argument consisting of '${WITHOUTPUTTOSINKBASEDONSTATUS_EXEC_END}' is encountered. Multiple
 			SINK-COMMANDs are joined with | as pipeline steps.
+    --default-command SINK-COMMAND
+			Execute SINK-COMMAND with the output piped into it if
+			no other --success-command, --fail-command, or
+			--status-command has been applied.
+			Multiple SINK-COMMANDs are joined with | as pipeline
+			steps.
+    --default-exec SINK-COMMAND [...] $WITHOUTPUTTOSINKBASEDONSTATUS_EXEC_END
+			Execute SINK-COMMAND with the output piped into it if
+			no other --success-exec, --fail-exec, or --status-exec
+			has been applied; all following arguments are taken to
+			be arguments to the SINK-COMMAND until an argument
+			consisting of '${WITHOUTPUTTOSINKBASEDONSTATUS_EXEC_END}' is encountered. Multiple SINK-COMMANDs
+			are joined with | as pipeline steps.
     --tee|-t		Also print the output in addition to piping it.
     --stdout|-1		Only pipe output to standard output; error output is
 			output normally.
@@ -127,6 +140,8 @@ do
 			status="$1"; shift
 			sinkRanges+=("$status")
 			statusSinkCommands["$status"]+="${statusSinkCommands["$status"]:+ $WITHOUTPUTTOSINKBASEDONSTATUS_SINKCOMMAND_JOINER }$1"; shift;;
+	--default-command) shift
+			statusSinkCommands['default']+="${statusSinkCommands['default']:+ $WITHOUTPUTTOSINKBASEDONSTATUS_SINKCOMMAND_JOINER }$1"; shift;;
 	--success-exec) shift
 			cmd=
 			while [ $# -gt 0 -a "$1" != "$WITHOUTPUTTOSINKBASEDONSTATUS_EXEC_END" ]
@@ -176,6 +191,21 @@ do
 			shift
 			sinkRanges+=("$status")
 			statusSinkCommands["$status"]+="${statusSinkCommands["$status"]:+ $WITHOUTPUTTOSINKBASEDONSTATUS_SINKCOMMAND_JOINER }$cmd"
+			;;
+	--default-exec)	shift
+			cmd=
+			while [ $# -gt 0 -a "$1" != "$WITHOUTPUTTOSINKBASEDONSTATUS_EXEC_END" ]
+			do
+			    printf -v quotedArg '%q' "$1"
+			    cmd="${cmd}${cmd:+ }${quotedArg}"
+			    shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo "ERROR: --default-exec command must be concluded with '${WITHOUTPUTTOSINKBASEDONSTATUS_EXEC_END}'"; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			shift
+			statusSinkCommands['default']+="${statusSinkCommands['default']:+ $WITHOUTPUTTOSINKBASEDONSTATUS_SINKCOMMAND_JOINER }$cmd"
 			;;
 	--command|-c)	shift; commands+="${commands:+ $WITHOUTPUTTOSINKBASEDONSTATUS_COMMAND_JOINER }$1"; shift;;
 	--exec)		shift
@@ -273,4 +303,7 @@ do
 			    ;;
     esac
 done
+
+[ -z "${statusSinkCommands[default]}" ] \
+    || range=default sinkExecute
 exit 99
